using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// Schema for ChatCompletionRequestMessageContentPartRefusal.
///
/// <para>Fields: - type (required): Literal["refusal"] - refusal (required): str</para>
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<
        ChatCompletionContentPartRefusalParam,
        ChatCompletionContentPartRefusalParamFromRaw
    >)
)]
public sealed record class ChatCompletionContentPartRefusalParam : JsonModel
{
    /// <summary>
    /// The refusal message generated by the model.
    /// </summary>
    public required string Refusal
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("refusal");
        }
        init { this._rawData.Set("refusal", value); }
    }

    /// <summary>
    /// The type of the content part.
    /// </summary>
    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Refusal;
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("refusal")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
    }

    public ChatCompletionContentPartRefusalParam()
    {
        this.Type = JsonSerializer.SerializeToElement("refusal");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChatCompletionContentPartRefusalParam(
        ChatCompletionContentPartRefusalParam chatCompletionContentPartRefusalParam
    )
        : base(chatCompletionContentPartRefusalParam) { }
#pragma warning restore CS8618

    public ChatCompletionContentPartRefusalParam(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("refusal");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChatCompletionContentPartRefusalParam(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChatCompletionContentPartRefusalParamFromRaw.FromRawUnchecked"/>
    public static ChatCompletionContentPartRefusalParam FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public ChatCompletionContentPartRefusalParam(string refusal)
        : this()
    {
        this.Refusal = refusal;
    }
}

class ChatCompletionContentPartRefusalParamFromRaw
    : IFromRawJson<ChatCompletionContentPartRefusalParam>
{
    /// <inheritdoc/>
    public ChatCompletionContentPartRefusalParam FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChatCompletionContentPartRefusalParam.FromRawUnchecked(rawData);
}
