using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;
using System = System;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// Messages sent by the model in response to user messages.
///
/// <para>Fields: - content (optional): str | Annotated[list[ChatCompletionRequestAssistantMessageContentPart],
/// MinLen(1), ArrayTitle("ChatCompletionRequestAssistantMessageContentArray")] |
/// None - refusal (optional): str | None - role (required): Literal["assistant"]
/// - name (optional): str - audio (optional): Audio | None - tool_calls (optional):
/// ChatCompletionMessageToolCalls - function_call (optional): FunctionCall | None</para>
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<
        ChatCompletionAssistantMessageParam,
        ChatCompletionAssistantMessageParamFromRaw
    >)
)]
public sealed record class ChatCompletionAssistantMessageParam : JsonModel
{
    /// <summary>
    /// The role of the messages author, in this case `assistant`.
    /// </summary>
    public JsonElement Role
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("role");
        }
        init { this._rawData.Set("role", value); }
    }

    /// <summary>
    /// Data about a previous audio response from the model. [Learn more](/docs/guides/audio).
    ///
    /// <para>Fields: - id (required): str</para>
    /// </summary>
    public CompletionAudio? Audio
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<CompletionAudio>("audio");
        }
        init { this._rawData.Set("audio", value); }
    }

    /// <summary>
    /// The contents of the assistant message. Required unless `tool_calls` or `function_call`
    /// is specified.
    /// </summary>
    public Content? Content
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<Content>("content");
        }
        init { this._rawData.Set("content", value); }
    }

    /// <summary>
    /// Deprecated and replaced by `tool_calls`. The name and arguments of a function
    /// that should be called, as generated by the model.
    ///
    /// <para>Fields: - arguments (required): str - name (required): str</para>
    /// </summary>
    public FunctionCall? FunctionCall
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FunctionCall>("function_call");
        }
        init { this._rawData.Set("function_call", value); }
    }

    /// <summary>
    /// An optional name for the participant. Provides the model information to differentiate
    /// between participants of the same role.
    /// </summary>
    public string? Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("name");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("name", value);
        }
    }

    /// <summary>
    /// The refusal message by the assistant.
    /// </summary>
    public string? Refusal
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("refusal");
        }
        init { this._rawData.Set("refusal", value); }
    }

    /// <summary>
    /// The tool calls generated by the model, such as function calls.
    /// </summary>
    public IReadOnlyList<ToolCall>? ToolCalls
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<ToolCall>>("tool_calls");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<ToolCall>?>(
                "tool_calls",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        if (!JsonElement.DeepEquals(this.Role, JsonSerializer.SerializeToElement("assistant")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
        this.Audio?.Validate();
        this.Content?.Validate();
        this.FunctionCall?.Validate();
        _ = this.Name;
        _ = this.Refusal;
        foreach (var item in this.ToolCalls ?? [])
        {
            item.Validate();
        }
    }

    public ChatCompletionAssistantMessageParam()
    {
        this.Role = JsonSerializer.SerializeToElement("assistant");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChatCompletionAssistantMessageParam(
        ChatCompletionAssistantMessageParam chatCompletionAssistantMessageParam
    )
        : base(chatCompletionAssistantMessageParam) { }
#pragma warning restore CS8618

    public ChatCompletionAssistantMessageParam(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Role = JsonSerializer.SerializeToElement("assistant");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChatCompletionAssistantMessageParam(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChatCompletionAssistantMessageParamFromRaw.FromRawUnchecked"/>
    public static ChatCompletionAssistantMessageParam FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChatCompletionAssistantMessageParamFromRaw : IFromRawJson<ChatCompletionAssistantMessageParam>
{
    /// <inheritdoc/>
    public ChatCompletionAssistantMessageParam FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChatCompletionAssistantMessageParam.FromRawUnchecked(rawData);
}

/// <summary>
/// The contents of the assistant message. Required unless `tool_calls` or `function_call`
/// is specified.
/// </summary>
[JsonConverter(typeof(ContentConverter))]
public record class Content : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public Content(string value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public Content(IReadOnlyList<UnnamedSchemaWithArrayParent1> value, JsonElement? element = null)
    {
        this.Value = ImmutableArray.ToImmutableArray(value);
        this._element = element;
    }

    public Content(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="string"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickString(out var value)) {
    ///     // `value` is of type `string`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickString([NotNullWhen(true)] out string? value)
    {
        value = this.Value as string;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="List{T}"/> where <c>T</c> is a <c>UnnamedSchemaWithArrayParent1</c>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickChatCompletionRequestAssistantMessageContentArray(out var value)) {
    ///     // `value` is of type `IReadOnlyList&lt;UnnamedSchemaWithArrayParent1&gt;`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickChatCompletionRequestAssistantMessageContentArray(
        [NotNullWhen(true)] out IReadOnlyList<UnnamedSchemaWithArrayParent1>? value
    )
    {
        value = this.Value as IReadOnlyList<UnnamedSchemaWithArrayParent1>;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (string value) =&gt; {...},
    ///     (IReadOnlyList&lt;UnnamedSchemaWithArrayParent1&gt; value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        System::Action<string> @string,
        System::Action<
            IReadOnlyList<UnnamedSchemaWithArrayParent1>
        > chatCompletionRequestAssistantMessageContentArray
    )
    {
        switch (this.Value)
        {
            case string value:
                @string(value);
                break;
            case IReadOnlyList<UnnamedSchemaWithArrayParent1> value:
                chatCompletionRequestAssistantMessageContentArray(value);
                break;
            default:
                throw new DedalusInvalidDataException("Data did not match any variant of Content");
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (string value) =&gt; {...},
    ///     (IReadOnlyList&lt;UnnamedSchemaWithArrayParent1&gt; value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        System::Func<string, T> @string,
        System::Func<
            IReadOnlyList<UnnamedSchemaWithArrayParent1>,
            T
        > chatCompletionRequestAssistantMessageContentArray
    )
    {
        return this.Value switch
        {
            string value => @string(value),
            IReadOnlyList<UnnamedSchemaWithArrayParent1> value =>
                chatCompletionRequestAssistantMessageContentArray(value),
            _ => throw new DedalusInvalidDataException("Data did not match any variant of Content"),
        };
    }

    public static implicit operator Content(string value) => new(value);

    public static implicit operator Content(List<UnnamedSchemaWithArrayParent1> value) =>
        new((IReadOnlyList<UnnamedSchemaWithArrayParent1>)value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new DedalusInvalidDataException("Data did not match any variant of Content");
        }
        this.Switch(
            (_) => { },
            (chatCompletionRequestAssistantMessageContentArray) =>
            {
                foreach (var item in chatCompletionRequestAssistantMessageContentArray)
                {
                    item.Validate();
                }
            }
        );
    }

    public virtual bool Equals(Content? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            string _ => 0,
            IReadOnlyList<UnnamedSchemaWithArrayParent1> _ => 1,
            _ => -1,
        };
    }
}

sealed class ContentConverter : JsonConverter<Content?>
{
    public override Content? Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        try
        {
            var deserialized = JsonSerializer.Deserialize<string>(element, options);
            if (deserialized != null)
            {
                return new(deserialized, element);
            }
        }
        catch (System::Exception e) when (e is JsonException || e is DedalusInvalidDataException)
        {
            // ignore
        }

        try
        {
            var deserialized = JsonSerializer.Deserialize<List<UnnamedSchemaWithArrayParent1>>(
                element,
                options
            );
            if (deserialized != null)
            {
                foreach (var item in deserialized)
                {
                    item.Validate();
                }
                return new(deserialized, element);
            }
        }
        catch (System::Exception e) when (e is JsonException || e is DedalusInvalidDataException)
        {
            // ignore
        }

        return new(element);
    }

    public override void Write(Utf8JsonWriter writer, Content? value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value?.Json, options);
    }
}

/// <summary>
/// Learn about [text inputs](/docs/guides/text-generation).
///
/// <para>Fields: - type (required): Literal["text"] - text (required): str</para>
/// </summary>
[JsonConverter(typeof(UnnamedSchemaWithArrayParent1Converter))]
public record class UnnamedSchemaWithArrayParent1 : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public JsonElement Type
    {
        get
        {
            return Match(
                chatCompletionContentPartTextParam: (x) => x.Type,
                chatCompletionContentPartRefusalParam: (x) => x.Type
            );
        }
    }

    public UnnamedSchemaWithArrayParent1(
        ChatCompletionContentPartTextParam value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public UnnamedSchemaWithArrayParent1(
        ChatCompletionContentPartRefusalParam value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public UnnamedSchemaWithArrayParent1(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="ChatCompletionContentPartTextParam"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickChatCompletionContentPartTextParam(out var value)) {
    ///     // `value` is of type `ChatCompletionContentPartTextParam`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickChatCompletionContentPartTextParam(
        [NotNullWhen(true)] out ChatCompletionContentPartTextParam? value
    )
    {
        value = this.Value as ChatCompletionContentPartTextParam;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="ChatCompletionContentPartRefusalParam"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickChatCompletionContentPartRefusalParam(out var value)) {
    ///     // `value` is of type `ChatCompletionContentPartRefusalParam`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickChatCompletionContentPartRefusalParam(
        [NotNullWhen(true)] out ChatCompletionContentPartRefusalParam? value
    )
    {
        value = this.Value as ChatCompletionContentPartRefusalParam;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (ChatCompletionContentPartTextParam value) =&gt; {...},
    ///     (ChatCompletionContentPartRefusalParam value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        System::Action<ChatCompletionContentPartTextParam> chatCompletionContentPartTextParam,
        System::Action<ChatCompletionContentPartRefusalParam> chatCompletionContentPartRefusalParam
    )
    {
        switch (this.Value)
        {
            case ChatCompletionContentPartTextParam value:
                chatCompletionContentPartTextParam(value);
                break;
            case ChatCompletionContentPartRefusalParam value:
                chatCompletionContentPartRefusalParam(value);
                break;
            default:
                throw new DedalusInvalidDataException(
                    "Data did not match any variant of UnnamedSchemaWithArrayParent1"
                );
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (ChatCompletionContentPartTextParam value) =&gt; {...},
    ///     (ChatCompletionContentPartRefusalParam value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        System::Func<ChatCompletionContentPartTextParam, T> chatCompletionContentPartTextParam,
        System::Func<ChatCompletionContentPartRefusalParam, T> chatCompletionContentPartRefusalParam
    )
    {
        return this.Value switch
        {
            ChatCompletionContentPartTextParam value => chatCompletionContentPartTextParam(value),
            ChatCompletionContentPartRefusalParam value => chatCompletionContentPartRefusalParam(
                value
            ),
            _ => throw new DedalusInvalidDataException(
                "Data did not match any variant of UnnamedSchemaWithArrayParent1"
            ),
        };
    }

    public static implicit operator UnnamedSchemaWithArrayParent1(
        ChatCompletionContentPartTextParam value
    ) => new(value);

    public static implicit operator UnnamedSchemaWithArrayParent1(
        ChatCompletionContentPartRefusalParam value
    ) => new(value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new DedalusInvalidDataException(
                "Data did not match any variant of UnnamedSchemaWithArrayParent1"
            );
        }
        this.Switch(
            (chatCompletionContentPartTextParam) => chatCompletionContentPartTextParam.Validate(),
            (chatCompletionContentPartRefusalParam) =>
                chatCompletionContentPartRefusalParam.Validate()
        );
    }

    public virtual bool Equals(UnnamedSchemaWithArrayParent1? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            ChatCompletionContentPartTextParam _ => 0,
            ChatCompletionContentPartRefusalParam _ => 1,
            _ => -1,
        };
    }
}

sealed class UnnamedSchemaWithArrayParent1Converter : JsonConverter<UnnamedSchemaWithArrayParent1>
{
    public override UnnamedSchemaWithArrayParent1? Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        string? type;
        try
        {
            type = element.GetProperty("type").GetString();
        }
        catch
        {
            type = null;
        }

        switch (type)
        {
            case "text":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<ChatCompletionContentPartTextParam>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            case "refusal":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<ChatCompletionContentPartRefusalParam>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            default:
            {
                return new UnnamedSchemaWithArrayParent1(element);
            }
        }
    }

    public override void Write(
        Utf8JsonWriter writer,
        UnnamedSchemaWithArrayParent1 value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Json, options);
    }
}

/// <summary>
/// Deprecated and replaced by `tool_calls`. The name and arguments of a function
/// that should be called, as generated by the model.
///
/// <para>Fields: - arguments (required): str - name (required): str</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<FunctionCall, FunctionCallFromRaw>))]
public sealed record class FunctionCall : JsonModel
{
    /// <summary>
    /// The arguments to call the function with, as generated by the model in JSON
    /// format. Note that the model does not always generate valid JSON, and may hallucinate
    /// parameters not defined by your function schema. Validate the arguments in
    /// your code before calling your function.
    /// </summary>
    public required string Arguments
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("arguments");
        }
        init { this._rawData.Set("arguments", value); }
    }

    /// <summary>
    /// The name of the function to call.
    /// </summary>
    public required string Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("name");
        }
        init { this._rawData.Set("name", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Arguments;
        _ = this.Name;
    }

    public FunctionCall() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public FunctionCall(FunctionCall functionCall)
        : base(functionCall) { }
#pragma warning restore CS8618

    public FunctionCall(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    FunctionCall(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="FunctionCallFromRaw.FromRawUnchecked"/>
    public static FunctionCall FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class FunctionCallFromRaw : IFromRawJson<FunctionCall>
{
    /// <inheritdoc/>
    public FunctionCall FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        FunctionCall.FromRawUnchecked(rawData);
}

/// <summary>
/// A call to a function tool created by the model.
///
/// <para>Fields: - id (required): str - type (required): Literal["function"] - function
/// (required): ChatCompletionMessageToolCallFunction - thought_signature (optional): str</para>
/// </summary>
[JsonConverter(typeof(ToolCallConverter))]
public record class ToolCall : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public string ID
    {
        get
        {
            return Match(
                chatCompletionMessage: (x) => x.ID,
                chatCompletionMessageCustom: (x) => x.ID
            );
        }
    }

    public JsonElement Type
    {
        get
        {
            return Match(
                chatCompletionMessage: (x) => x.Type,
                chatCompletionMessageCustom: (x) => x.Type
            );
        }
    }

    public ToolCall(CompletionChatCompletionMessageToolCall value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public ToolCall(ChatCompletionMessageCustomToolCall value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public ToolCall(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="CompletionChatCompletionMessageToolCall"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickChatCompletionMessage(out var value)) {
    ///     // `value` is of type `CompletionChatCompletionMessageToolCall`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickChatCompletionMessage(
        [NotNullWhen(true)] out CompletionChatCompletionMessageToolCall? value
    )
    {
        value = this.Value as CompletionChatCompletionMessageToolCall;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="ChatCompletionMessageCustomToolCall"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickChatCompletionMessageCustom(out var value)) {
    ///     // `value` is of type `ChatCompletionMessageCustomToolCall`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickChatCompletionMessageCustom(
        [NotNullWhen(true)] out ChatCompletionMessageCustomToolCall? value
    )
    {
        value = this.Value as ChatCompletionMessageCustomToolCall;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (CompletionChatCompletionMessageToolCall value) =&gt; {...},
    ///     (ChatCompletionMessageCustomToolCall value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        System::Action<CompletionChatCompletionMessageToolCall> chatCompletionMessage,
        System::Action<ChatCompletionMessageCustomToolCall> chatCompletionMessageCustom
    )
    {
        switch (this.Value)
        {
            case CompletionChatCompletionMessageToolCall value:
                chatCompletionMessage(value);
                break;
            case ChatCompletionMessageCustomToolCall value:
                chatCompletionMessageCustom(value);
                break;
            default:
                throw new DedalusInvalidDataException("Data did not match any variant of ToolCall");
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (CompletionChatCompletionMessageToolCall value) =&gt; {...},
    ///     (ChatCompletionMessageCustomToolCall value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        System::Func<CompletionChatCompletionMessageToolCall, T> chatCompletionMessage,
        System::Func<ChatCompletionMessageCustomToolCall, T> chatCompletionMessageCustom
    )
    {
        return this.Value switch
        {
            CompletionChatCompletionMessageToolCall value => chatCompletionMessage(value),
            ChatCompletionMessageCustomToolCall value => chatCompletionMessageCustom(value),
            _ => throw new DedalusInvalidDataException(
                "Data did not match any variant of ToolCall"
            ),
        };
    }

    public static implicit operator ToolCall(CompletionChatCompletionMessageToolCall value) =>
        new(value);

    public static implicit operator ToolCall(ChatCompletionMessageCustomToolCall value) =>
        new(value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new DedalusInvalidDataException("Data did not match any variant of ToolCall");
        }
        this.Switch(
            (chatCompletionMessage) => chatCompletionMessage.Validate(),
            (chatCompletionMessageCustom) => chatCompletionMessageCustom.Validate()
        );
    }

    public virtual bool Equals(ToolCall? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            CompletionChatCompletionMessageToolCall _ => 0,
            ChatCompletionMessageCustomToolCall _ => 1,
            _ => -1,
        };
    }
}

sealed class ToolCallConverter : JsonConverter<ToolCall>
{
    public override ToolCall? Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        string? type;
        try
        {
            type = element.GetProperty("type").GetString();
        }
        catch
        {
            type = null;
        }

        switch (type)
        {
            case "function":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<CompletionChatCompletionMessageToolCall>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            case "custom":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<ChatCompletionMessageCustomToolCall>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            default:
            {
                return new ToolCall(element);
            }
        }
    }

    public override void Write(Utf8JsonWriter writer, ToolCall value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value.Json, options);
    }
}
