using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;
using System = System;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// A chat completion message generated by the model.
///
/// <para>Fields: - content (required): str | None - refusal (required): str | None
/// - tool_calls (optional): ChatCompletionMessageToolCalls - annotations (optional):
/// list[AnnotationsItem] - role (required): Literal["assistant"] - function_call
/// (optional): ChatCompletionResponseMessageFunctionCall - audio (optional): ChatCompletionResponseMessageAudio
/// | None</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<ChatCompletionMessage, ChatCompletionMessageFromRaw>))]
public sealed record class ChatCompletionMessage : JsonModel
{
    /// <summary>
    /// The contents of the message.
    /// </summary>
    public required string? Content
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("content");
        }
        init { this._rawData.Set("content", value); }
    }

    /// <summary>
    /// The refusal message generated by the model.
    /// </summary>
    public required string? Refusal
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("refusal");
        }
        init { this._rawData.Set("refusal", value); }
    }

    /// <summary>
    /// The role of the author of this message.
    /// </summary>
    public JsonElement Role
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("role");
        }
        init { this._rawData.Set("role", value); }
    }

    /// <summary>
    /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
    /// </summary>
    public IReadOnlyList<Annotation>? Annotations
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<Annotation>>("annotations");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<Annotation>?>(
                "annotations",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// If the audio output modality is requested, this object contains data about
    /// the audio response from the model. [Learn more](/docs/guides/audio).
    ///
    /// <para>Fields: - id (required): str - expires_at (required): int - data (required):
    /// str - transcript (required): str</para>
    /// </summary>
    public ChatCompletionMessageAudio? Audio
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ChatCompletionMessageAudio>("audio");
        }
        init { this._rawData.Set("audio", value); }
    }

    /// <summary>
    /// Deprecated and replaced by `tool_calls`. The name and arguments of a function
    /// that should be called, as generated by the model.
    ///
    /// <para>Fields: - arguments (required): str - name (required): str</para>
    /// </summary>
    public ChatCompletionMessageFunctionCall? FunctionCall
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ChatCompletionMessageFunctionCall>(
                "function_call"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("function_call", value);
        }
    }

    /// <summary>
    /// The tool calls generated by the model, such as function calls.
    /// </summary>
    public IReadOnlyList<ChatCompletionMessageToolCall>? ToolCalls
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<ChatCompletionMessageToolCall>>(
                "tool_calls"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<ChatCompletionMessageToolCall>?>(
                "tool_calls",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Content;
        _ = this.Refusal;
        if (!JsonElement.DeepEquals(this.Role, JsonSerializer.SerializeToElement("assistant")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
        foreach (var item in this.Annotations ?? [])
        {
            item.Validate();
        }
        this.Audio?.Validate();
        this.FunctionCall?.Validate();
        foreach (var item in this.ToolCalls ?? [])
        {
            item.Validate();
        }
    }

    public ChatCompletionMessage()
    {
        this.Role = JsonSerializer.SerializeToElement("assistant");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChatCompletionMessage(ChatCompletionMessage chatCompletionMessage)
        : base(chatCompletionMessage) { }
#pragma warning restore CS8618

    public ChatCompletionMessage(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Role = JsonSerializer.SerializeToElement("assistant");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChatCompletionMessage(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChatCompletionMessageFromRaw.FromRawUnchecked"/>
    public static ChatCompletionMessage FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChatCompletionMessageFromRaw : IFromRawJson<ChatCompletionMessage>
{
    /// <inheritdoc/>
    public ChatCompletionMessage FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChatCompletionMessage.FromRawUnchecked(rawData);
}

/// <summary>
/// A URL citation when using web search.
///
/// <para>Fields: - type (required): Literal["url_citation"] - url_citation (required): UrlCitation</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Annotation, AnnotationFromRaw>))]
public sealed record class Annotation : JsonModel
{
    /// <summary>
    /// The type of the URL citation. Always `url_citation`.
    /// </summary>
    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <summary>
    /// A URL citation when using web search.
    ///
    /// <para>Fields: - end_index (required): int - start_index (required): int -
    /// url (required): str - title (required): str</para>
    /// </summary>
    public required UrlCitation UrlCitation
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<UrlCitation>("url_citation");
        }
        init { this._rawData.Set("url_citation", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("url_citation")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
        this.UrlCitation.Validate();
    }

    public Annotation()
    {
        this.Type = JsonSerializer.SerializeToElement("url_citation");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Annotation(Annotation annotation)
        : base(annotation) { }
#pragma warning restore CS8618

    public Annotation(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("url_citation");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Annotation(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="AnnotationFromRaw.FromRawUnchecked"/>
    public static Annotation FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public Annotation(UrlCitation urlCitation)
        : this()
    {
        this.UrlCitation = urlCitation;
    }
}

class AnnotationFromRaw : IFromRawJson<Annotation>
{
    /// <inheritdoc/>
    public Annotation FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Annotation.FromRawUnchecked(rawData);
}

/// <summary>
/// A URL citation when using web search.
///
/// <para>Fields: - end_index (required): int - start_index (required): int - url
/// (required): str - title (required): str</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<UrlCitation, UrlCitationFromRaw>))]
public sealed record class UrlCitation : JsonModel
{
    /// <summary>
    /// The index of the last character of the URL citation in the message.
    /// </summary>
    public required long EndIndex
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("end_index");
        }
        init { this._rawData.Set("end_index", value); }
    }

    /// <summary>
    /// The index of the first character of the URL citation in the message.
    /// </summary>
    public required long StartIndex
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("start_index");
        }
        init { this._rawData.Set("start_index", value); }
    }

    /// <summary>
    /// The title of the web resource.
    /// </summary>
    public required string Title
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("title");
        }
        init { this._rawData.Set("title", value); }
    }

    /// <summary>
    /// The URL of the web resource.
    /// </summary>
    public required string Url
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("url");
        }
        init { this._rawData.Set("url", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.EndIndex;
        _ = this.StartIndex;
        _ = this.Title;
        _ = this.Url;
    }

    public UrlCitation() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public UrlCitation(UrlCitation urlCitation)
        : base(urlCitation) { }
#pragma warning restore CS8618

    public UrlCitation(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    UrlCitation(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="UrlCitationFromRaw.FromRawUnchecked"/>
    public static UrlCitation FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class UrlCitationFromRaw : IFromRawJson<UrlCitation>
{
    /// <inheritdoc/>
    public UrlCitation FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        UrlCitation.FromRawUnchecked(rawData);
}

/// <summary>
/// If the audio output modality is requested, this object contains data about the
/// audio response from the model. [Learn more](/docs/guides/audio).
///
/// <para>Fields: - id (required): str - expires_at (required): int - data (required):
/// str - transcript (required): str</para>
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<ChatCompletionMessageAudio, ChatCompletionMessageAudioFromRaw>)
)]
public sealed record class ChatCompletionMessageAudio : JsonModel
{
    /// <summary>
    /// Unique identifier for this audio response.
    /// </summary>
    public required string ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("id");
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// Base64 encoded audio bytes generated by the model, in the format specified
    /// in the request.
    /// </summary>
    public required string Data
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("data");
        }
        init { this._rawData.Set("data", value); }
    }

    /// <summary>
    /// The Unix timestamp (in seconds) for when this audio response will no longer
    /// be accessible on the server for use in multi-turn conversations.
    /// </summary>
    public required long ExpiresAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("expires_at");
        }
        init { this._rawData.Set("expires_at", value); }
    }

    /// <summary>
    /// Transcript of the audio generated by the model.
    /// </summary>
    public required string Transcript
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("transcript");
        }
        init { this._rawData.Set("transcript", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.Data;
        _ = this.ExpiresAt;
        _ = this.Transcript;
    }

    public ChatCompletionMessageAudio() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChatCompletionMessageAudio(ChatCompletionMessageAudio chatCompletionMessageAudio)
        : base(chatCompletionMessageAudio) { }
#pragma warning restore CS8618

    public ChatCompletionMessageAudio(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChatCompletionMessageAudio(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChatCompletionMessageAudioFromRaw.FromRawUnchecked"/>
    public static ChatCompletionMessageAudio FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChatCompletionMessageAudioFromRaw : IFromRawJson<ChatCompletionMessageAudio>
{
    /// <inheritdoc/>
    public ChatCompletionMessageAudio FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChatCompletionMessageAudio.FromRawUnchecked(rawData);
}

/// <summary>
/// Deprecated and replaced by `tool_calls`. The name and arguments of a function
/// that should be called, as generated by the model.
///
/// <para>Fields: - arguments (required): str - name (required): str</para>
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<
        ChatCompletionMessageFunctionCall,
        ChatCompletionMessageFunctionCallFromRaw
    >)
)]
public sealed record class ChatCompletionMessageFunctionCall : JsonModel
{
    /// <summary>
    /// The arguments to call the function with, as generated by the model in JSON
    /// format. Note that the model does not always generate valid JSON, and may hallucinate
    /// parameters not defined by your function schema. Validate the arguments in
    /// your code before calling your function.
    /// </summary>
    public required string Arguments
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("arguments");
        }
        init { this._rawData.Set("arguments", value); }
    }

    /// <summary>
    /// The name of the function to call.
    /// </summary>
    public required string Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("name");
        }
        init { this._rawData.Set("name", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Arguments;
        _ = this.Name;
    }

    public ChatCompletionMessageFunctionCall() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChatCompletionMessageFunctionCall(
        ChatCompletionMessageFunctionCall chatCompletionMessageFunctionCall
    )
        : base(chatCompletionMessageFunctionCall) { }
#pragma warning restore CS8618

    public ChatCompletionMessageFunctionCall(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChatCompletionMessageFunctionCall(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChatCompletionMessageFunctionCallFromRaw.FromRawUnchecked"/>
    public static ChatCompletionMessageFunctionCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChatCompletionMessageFunctionCallFromRaw : IFromRawJson<ChatCompletionMessageFunctionCall>
{
    /// <inheritdoc/>
    public ChatCompletionMessageFunctionCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChatCompletionMessageFunctionCall.FromRawUnchecked(rawData);
}

/// <summary>
/// A call to a function tool created by the model.
///
/// <para>Fields: - id (required): str - type (required): Literal["function"] - function
/// (required): ChatCompletionMessageToolCallFunction - thought_signature (optional): str</para>
/// </summary>
[JsonConverter(typeof(ChatCompletionMessageToolCallConverter))]
public record class ChatCompletionMessageToolCall : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public string ID
    {
        get
        {
            return Match(
                chatCompletionMessage: (x) => x.ID,
                chatCompletionMessageCustom: (x) => x.ID
            );
        }
    }

    public JsonElement Type
    {
        get
        {
            return Match(
                chatCompletionMessage: (x) => x.Type,
                chatCompletionMessageCustom: (x) => x.Type
            );
        }
    }

    public ChatCompletionMessageToolCall(
        CompletionChatCompletionMessageToolCall value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public ChatCompletionMessageToolCall(
        ChatCompletionMessageCustomToolCall value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public ChatCompletionMessageToolCall(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="CompletionChatCompletionMessageToolCall"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickChatCompletionMessage(out var value)) {
    ///     // `value` is of type `CompletionChatCompletionMessageToolCall`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickChatCompletionMessage(
        [NotNullWhen(true)] out CompletionChatCompletionMessageToolCall? value
    )
    {
        value = this.Value as CompletionChatCompletionMessageToolCall;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="ChatCompletionMessageCustomToolCall"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickChatCompletionMessageCustom(out var value)) {
    ///     // `value` is of type `ChatCompletionMessageCustomToolCall`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickChatCompletionMessageCustom(
        [NotNullWhen(true)] out ChatCompletionMessageCustomToolCall? value
    )
    {
        value = this.Value as ChatCompletionMessageCustomToolCall;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (CompletionChatCompletionMessageToolCall value) =&gt; {...},
    ///     (ChatCompletionMessageCustomToolCall value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        System::Action<CompletionChatCompletionMessageToolCall> chatCompletionMessage,
        System::Action<ChatCompletionMessageCustomToolCall> chatCompletionMessageCustom
    )
    {
        switch (this.Value)
        {
            case CompletionChatCompletionMessageToolCall value:
                chatCompletionMessage(value);
                break;
            case ChatCompletionMessageCustomToolCall value:
                chatCompletionMessageCustom(value);
                break;
            default:
                throw new DedalusInvalidDataException(
                    "Data did not match any variant of ChatCompletionMessageToolCall"
                );
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (CompletionChatCompletionMessageToolCall value) =&gt; {...},
    ///     (ChatCompletionMessageCustomToolCall value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        System::Func<CompletionChatCompletionMessageToolCall, T> chatCompletionMessage,
        System::Func<ChatCompletionMessageCustomToolCall, T> chatCompletionMessageCustom
    )
    {
        return this.Value switch
        {
            CompletionChatCompletionMessageToolCall value => chatCompletionMessage(value),
            ChatCompletionMessageCustomToolCall value => chatCompletionMessageCustom(value),
            _ => throw new DedalusInvalidDataException(
                "Data did not match any variant of ChatCompletionMessageToolCall"
            ),
        };
    }

    public static implicit operator ChatCompletionMessageToolCall(
        CompletionChatCompletionMessageToolCall value
    ) => new(value);

    public static implicit operator ChatCompletionMessageToolCall(
        ChatCompletionMessageCustomToolCall value
    ) => new(value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new DedalusInvalidDataException(
                "Data did not match any variant of ChatCompletionMessageToolCall"
            );
        }
        this.Switch(
            (chatCompletionMessage) => chatCompletionMessage.Validate(),
            (chatCompletionMessageCustom) => chatCompletionMessageCustom.Validate()
        );
    }

    public virtual bool Equals(ChatCompletionMessageToolCall? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            CompletionChatCompletionMessageToolCall _ => 0,
            ChatCompletionMessageCustomToolCall _ => 1,
            _ => -1,
        };
    }
}

sealed class ChatCompletionMessageToolCallConverter : JsonConverter<ChatCompletionMessageToolCall>
{
    public override ChatCompletionMessageToolCall? Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        string? type;
        try
        {
            type = element.GetProperty("type").GetString();
        }
        catch
        {
            type = null;
        }

        switch (type)
        {
            case "function":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<CompletionChatCompletionMessageToolCall>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            case "custom":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<ChatCompletionMessageCustomToolCall>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            default:
            {
                return new ChatCompletionMessageToolCall(element);
            }
        }
    }

    public override void Write(
        Utf8JsonWriter writer,
        ChatCompletionMessageToolCall value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Json, options);
    }
}
