using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// A call to a custom tool created by the model.
///
/// <para>Fields: - id (required): str - type (required): Literal["custom"] - custom
/// (required): ChatCompletionMessageCustomToolCallCustom</para>
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<
        ChatCompletionMessageCustomToolCall,
        ChatCompletionMessageCustomToolCallFromRaw
    >)
)]
public sealed record class ChatCompletionMessageCustomToolCall : JsonModel
{
    /// <summary>
    /// The ID of the tool call.
    /// </summary>
    public required string ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("id");
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// The custom tool that the model called.
    ///
    /// <para>Fields: - name (required): str - input (required): str</para>
    /// </summary>
    public required Custom Custom
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<Custom>("custom");
        }
        init { this._rawData.Set("custom", value); }
    }

    /// <summary>
    /// The type of the tool. Always `custom`.
    /// </summary>
    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        this.Custom.Validate();
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("custom")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
    }

    public ChatCompletionMessageCustomToolCall()
    {
        this.Type = JsonSerializer.SerializeToElement("custom");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChatCompletionMessageCustomToolCall(
        ChatCompletionMessageCustomToolCall chatCompletionMessageCustomToolCall
    )
        : base(chatCompletionMessageCustomToolCall) { }
#pragma warning restore CS8618

    public ChatCompletionMessageCustomToolCall(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("custom");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChatCompletionMessageCustomToolCall(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChatCompletionMessageCustomToolCallFromRaw.FromRawUnchecked"/>
    public static ChatCompletionMessageCustomToolCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChatCompletionMessageCustomToolCallFromRaw : IFromRawJson<ChatCompletionMessageCustomToolCall>
{
    /// <inheritdoc/>
    public ChatCompletionMessageCustomToolCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChatCompletionMessageCustomToolCall.FromRawUnchecked(rawData);
}

/// <summary>
/// The custom tool that the model called.
///
/// <para>Fields: - name (required): str - input (required): str</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Custom, CustomFromRaw>))]
public sealed record class Custom : JsonModel
{
    /// <summary>
    /// The input for the custom tool call generated by the model.
    /// </summary>
    public required string Input
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("input");
        }
        init { this._rawData.Set("input", value); }
    }

    /// <summary>
    /// The name of the custom tool to call.
    /// </summary>
    public required string Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("name");
        }
        init { this._rawData.Set("name", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Input;
        _ = this.Name;
    }

    public Custom() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Custom(Custom custom)
        : base(custom) { }
#pragma warning restore CS8618

    public Custom(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Custom(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="CustomFromRaw.FromRawUnchecked"/>
    public static Custom FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class CustomFromRaw : IFromRawJson<Custom>
{
    /// <inheritdoc/>
    public Custom FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Custom.FromRawUnchecked(rawData);
}
