using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;
using System = System;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// Schema for ChatCompletionMessageToolCallChunk.
///
/// <para>Fields: - index (required): int - id (optional): str - type (optional):
/// Literal["function"] - function (optional): ChatCompletionMessageToolCallChunkFunction</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<ChoiceDeltaToolCall, ChoiceDeltaToolCallFromRaw>))]
public sealed record class ChoiceDeltaToolCall : JsonModel
{
    public required long Index
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("index");
        }
        init { this._rawData.Set("index", value); }
    }

    /// <summary>
    /// The ID of the tool call.
    /// </summary>
    public string? ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("id");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("id", value);
        }
    }

    /// <summary>
    /// Schema for ChatCompletionMessageToolCallChunkFunction.
    ///
    /// <para>Fields: - name (optional): str - arguments (optional): str</para>
    /// </summary>
    public ChoiceDeltaToolCallFunction? Function
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ChoiceDeltaToolCallFunction>("function");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("function", value);
        }
    }

    /// <summary>
    /// The type of the tool. Currently, only `function` is supported.
    /// </summary>
    public ApiEnum<string, ChoiceDeltaToolCallType>? Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, ChoiceDeltaToolCallType>>("type");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("type", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Index;
        _ = this.ID;
        this.Function?.Validate();
        this.Type?.Validate();
    }

    public ChoiceDeltaToolCall() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChoiceDeltaToolCall(ChoiceDeltaToolCall choiceDeltaToolCall)
        : base(choiceDeltaToolCall) { }
#pragma warning restore CS8618

    public ChoiceDeltaToolCall(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChoiceDeltaToolCall(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChoiceDeltaToolCallFromRaw.FromRawUnchecked"/>
    public static ChoiceDeltaToolCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public ChoiceDeltaToolCall(long index)
        : this()
    {
        this.Index = index;
    }
}

class ChoiceDeltaToolCallFromRaw : IFromRawJson<ChoiceDeltaToolCall>
{
    /// <inheritdoc/>
    public ChoiceDeltaToolCall FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        ChoiceDeltaToolCall.FromRawUnchecked(rawData);
}

/// <summary>
/// Schema for ChatCompletionMessageToolCallChunkFunction.
///
/// <para>Fields: - name (optional): str - arguments (optional): str</para>
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<ChoiceDeltaToolCallFunction, ChoiceDeltaToolCallFunctionFromRaw>)
)]
public sealed record class ChoiceDeltaToolCallFunction : JsonModel
{
    /// <summary>
    /// The arguments to call the function with, as generated by the model in JSON
    /// format. Note that the model does not always generate valid JSON, and may hallucinate
    /// parameters not defined by your function schema. Validate the arguments in
    /// your code before calling your function.
    /// </summary>
    public string? Arguments
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("arguments");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("arguments", value);
        }
    }

    /// <summary>
    /// The name of the function to call.
    /// </summary>
    public string? Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("name");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("name", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Arguments;
        _ = this.Name;
    }

    public ChoiceDeltaToolCallFunction() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChoiceDeltaToolCallFunction(ChoiceDeltaToolCallFunction choiceDeltaToolCallFunction)
        : base(choiceDeltaToolCallFunction) { }
#pragma warning restore CS8618

    public ChoiceDeltaToolCallFunction(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChoiceDeltaToolCallFunction(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChoiceDeltaToolCallFunctionFromRaw.FromRawUnchecked"/>
    public static ChoiceDeltaToolCallFunction FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChoiceDeltaToolCallFunctionFromRaw : IFromRawJson<ChoiceDeltaToolCallFunction>
{
    /// <inheritdoc/>
    public ChoiceDeltaToolCallFunction FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChoiceDeltaToolCallFunction.FromRawUnchecked(rawData);
}

/// <summary>
/// The type of the tool. Currently, only `function` is supported.
/// </summary>
[JsonConverter(typeof(ChoiceDeltaToolCallTypeConverter))]
public enum ChoiceDeltaToolCallType
{
    Function,
}

sealed class ChoiceDeltaToolCallTypeConverter : JsonConverter<ChoiceDeltaToolCallType>
{
    public override ChoiceDeltaToolCallType Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "function" => ChoiceDeltaToolCallType.Function,
            _ => (ChoiceDeltaToolCallType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        ChoiceDeltaToolCallType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                ChoiceDeltaToolCallType.Function => "function",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
