using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;
using System = System;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// A chat completion delta generated by streamed model responses.
///
/// <para>Fields: - content (optional): str | None - function_call (optional): ChatCompletionStreamResponseDeltaFunctionCall
/// - tool_calls (optional): list[ChatCompletionMessageToolCallChunk] - role (optional):
/// Literal["developer", "system", "user", "assistant", "tool"] - refusal (optional):
/// str | None</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<ChoiceDelta, ChoiceDeltaFromRaw>))]
public sealed record class ChoiceDelta : JsonModel
{
    /// <summary>
    /// The contents of the chunk message.
    /// </summary>
    public string? Content
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("content");
        }
        init { this._rawData.Set("content", value); }
    }

    /// <summary>
    /// Deprecated and replaced by `tool_calls`. The name and arguments of a function
    /// that should be called, as generated by the model.
    ///
    /// <para>Fields: - arguments (optional): str - name (optional): str</para>
    /// </summary>
    public ChoiceDeltaFunctionCall? FunctionCall
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ChoiceDeltaFunctionCall>("function_call");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("function_call", value);
        }
    }

    /// <summary>
    /// The refusal message generated by the model.
    /// </summary>
    public string? Refusal
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("refusal");
        }
        init { this._rawData.Set("refusal", value); }
    }

    /// <summary>
    /// The role of the author of this message.
    /// </summary>
    public ApiEnum<string, Role>? Role
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, Role>>("role");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("role", value);
        }
    }

    public IReadOnlyList<ChoiceDeltaToolCall>? ToolCalls
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<ChoiceDeltaToolCall>>(
                "tool_calls"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<ChoiceDeltaToolCall>?>(
                "tool_calls",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Content;
        this.FunctionCall?.Validate();
        _ = this.Refusal;
        this.Role?.Validate();
        foreach (var item in this.ToolCalls ?? [])
        {
            item.Validate();
        }
    }

    public ChoiceDelta() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChoiceDelta(ChoiceDelta choiceDelta)
        : base(choiceDelta) { }
#pragma warning restore CS8618

    public ChoiceDelta(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChoiceDelta(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChoiceDeltaFromRaw.FromRawUnchecked"/>
    public static ChoiceDelta FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChoiceDeltaFromRaw : IFromRawJson<ChoiceDelta>
{
    /// <inheritdoc/>
    public ChoiceDelta FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        ChoiceDelta.FromRawUnchecked(rawData);
}

/// <summary>
/// Deprecated and replaced by `tool_calls`. The name and arguments of a function
/// that should be called, as generated by the model.
///
/// <para>Fields: - arguments (optional): str - name (optional): str</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<ChoiceDeltaFunctionCall, ChoiceDeltaFunctionCallFromRaw>))]
public sealed record class ChoiceDeltaFunctionCall : JsonModel
{
    /// <summary>
    /// The arguments to call the function with, as generated by the model in JSON
    /// format. Note that the model does not always generate valid JSON, and may hallucinate
    /// parameters not defined by your function schema. Validate the arguments in
    /// your code before calling your function.
    /// </summary>
    public string? Arguments
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("arguments");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("arguments", value);
        }
    }

    /// <summary>
    /// The name of the function to call.
    /// </summary>
    public string? Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("name");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("name", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Arguments;
        _ = this.Name;
    }

    public ChoiceDeltaFunctionCall() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ChoiceDeltaFunctionCall(ChoiceDeltaFunctionCall choiceDeltaFunctionCall)
        : base(choiceDeltaFunctionCall) { }
#pragma warning restore CS8618

    public ChoiceDeltaFunctionCall(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ChoiceDeltaFunctionCall(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChoiceDeltaFunctionCallFromRaw.FromRawUnchecked"/>
    public static ChoiceDeltaFunctionCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChoiceDeltaFunctionCallFromRaw : IFromRawJson<ChoiceDeltaFunctionCall>
{
    /// <inheritdoc/>
    public ChoiceDeltaFunctionCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ChoiceDeltaFunctionCall.FromRawUnchecked(rawData);
}

/// <summary>
/// The role of the author of this message.
/// </summary>
[JsonConverter(typeof(RoleConverter))]
public enum Role
{
    Developer,
    System,
    User,
    Assistant,
    Tool,
}

sealed class RoleConverter : JsonConverter<Role>
{
    public override Role Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "developer" => Role.Developer,
            "system" => Role.System,
            "user" => Role.User,
            "assistant" => Role.Assistant,
            "tool" => Role.Tool,
            _ => (Role)(-1),
        };
    }

    public override void Write(Utf8JsonWriter writer, Role value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Role.Developer => "developer",
                Role.System => "system",
                Role.User => "user",
                Role.Assistant => "assistant",
                Role.Tool => "tool",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
