using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;
using System = System;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// A chat completion choice.
///
/// <para>OpenAI-compatible choice object for non-streaming responses. Part of the
/// ChatCompletion response.</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Choice, ChoiceFromRaw>))]
public sealed record class Choice : JsonModel
{
    /// <summary>
    /// The index of the choice in the list of choices.
    /// </summary>
    public required long Index
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("index");
        }
        init { this._rawData.Set("index", value); }
    }

    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    public required ChatCompletionMessage Message
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ChatCompletionMessage>("message");
        }
        init { this._rawData.Set("message", value); }
    }

    /// <summary>
    /// The reason the model stopped generating tokens. This will be `stop` if the
    /// model hit a natural stop point or a provided stop sequence, `length` if the
    /// maximum number of tokens specified in the request was reached, `content_filter`
    /// if content was omitted due to a flag from our content filters, `tool_calls`
    /// if the model called a tool, or `function_call` (deprecated) if the model called
    /// a function.
    /// </summary>
    public ApiEnum<string, FinishReason>? FinishReason
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, FinishReason>>("finish_reason");
        }
        init { this._rawData.Set("finish_reason", value); }
    }

    /// <summary>
    /// Log probability information for the choice.
    /// </summary>
    public ChoiceLogprobs? Logprobs
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ChoiceLogprobs>("logprobs");
        }
        init { this._rawData.Set("logprobs", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Index;
        this.Message.Validate();
        this.FinishReason?.Validate();
        this.Logprobs?.Validate();
    }

    public Choice() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Choice(Choice choice)
        : base(choice) { }
#pragma warning restore CS8618

    public Choice(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Choice(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ChoiceFromRaw.FromRawUnchecked"/>
    public static Choice FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ChoiceFromRaw : IFromRawJson<Choice>
{
    /// <inheritdoc/>
    public Choice FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Choice.FromRawUnchecked(rawData);
}

/// <summary>
/// The reason the model stopped generating tokens. This will be `stop` if the model
/// hit a natural stop point or a provided stop sequence, `length` if the maximum
/// number of tokens specified in the request was reached, `content_filter` if content
/// was omitted due to a flag from our content filters, `tool_calls` if the model
/// called a tool, or `function_call` (deprecated) if the model called a function.
/// </summary>
[JsonConverter(typeof(FinishReasonConverter))]
public enum FinishReason
{
    Stop,
    Length,
    ToolCalls,
    ContentFilter,
    FunctionCall,
}

sealed class FinishReasonConverter : JsonConverter<FinishReason>
{
    public override FinishReason Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "stop" => FinishReason.Stop,
            "length" => FinishReason.Length,
            "tool_calls" => FinishReason.ToolCalls,
            "content_filter" => FinishReason.ContentFilter,
            "function_call" => FinishReason.FunctionCall,
            _ => (FinishReason)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        FinishReason value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                FinishReason.Stop => "stop",
                FinishReason.Length => "length",
                FinishReason.ToolCalls => "tool_calls",
                FinishReason.ContentFilter => "content_filter",
                FinishReason.FunctionCall => "function_call",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
