using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// Breakdown of tokens used in a completion.
///
/// <para>Fields: - accepted_prediction_tokens (optional): int - audio_tokens (optional):
/// int - reasoning_tokens (optional): int - rejected_prediction_tokens (optional): int</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<CompletionTokensDetails, CompletionTokensDetailsFromRaw>))]
public sealed record class CompletionTokensDetails : JsonModel
{
    /// <summary>
    /// When using Predicted Outputs, the number of tokens in the prediction that
    /// appeared in the completion.
    /// </summary>
    public long? AcceptedPredictionTokens
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("accepted_prediction_tokens");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("accepted_prediction_tokens", value);
        }
    }

    /// <summary>
    /// Audio input tokens generated by the model.
    /// </summary>
    public long? AudioTokens
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("audio_tokens");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("audio_tokens", value);
        }
    }

    /// <summary>
    /// Tokens generated by the model for reasoning.
    /// </summary>
    public long? ReasoningTokens
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("reasoning_tokens");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("reasoning_tokens", value);
        }
    }

    /// <summary>
    /// When using Predicted Outputs, the number of tokens in the prediction that
    /// did not appear in the completion. However, like reasoning tokens, these tokens
    /// are still counted in the total completion tokens for purposes of billing,
    /// output, and context window limits.
    /// </summary>
    public long? RejectedPredictionTokens
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("rejected_prediction_tokens");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("rejected_prediction_tokens", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.AcceptedPredictionTokens;
        _ = this.AudioTokens;
        _ = this.ReasoningTokens;
        _ = this.RejectedPredictionTokens;
    }

    public CompletionTokensDetails() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public CompletionTokensDetails(CompletionTokensDetails completionTokensDetails)
        : base(completionTokensDetails) { }
#pragma warning restore CS8618

    public CompletionTokensDetails(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    CompletionTokensDetails(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="CompletionTokensDetailsFromRaw.FromRawUnchecked"/>
    public static CompletionTokensDetails FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class CompletionTokensDetailsFromRaw : IFromRawJson<CompletionTokensDetails>
{
    /// <inheritdoc/>
    public CompletionTokensDetails FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => CompletionTokensDetails.FromRawUnchecked(rawData);
}
