using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// A call to a function tool created by the model.
///
/// <para>Fields: - id (required): str - type (required): Literal["function"] - function
/// (required): ChatCompletionMessageToolCallFunction - thought_signature (optional): str</para>
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<
        CompletionChatCompletionMessageToolCall,
        CompletionChatCompletionMessageToolCallFromRaw
    >)
)]
public sealed record class CompletionChatCompletionMessageToolCall : JsonModel
{
    /// <summary>
    /// The ID of the tool call.
    /// </summary>
    public required string ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("id");
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// The function that the model called.
    ///
    /// <para>Fields: - name (required): str - arguments (required): str</para>
    /// </summary>
    public required Function Function
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<Function>("function");
        }
        init { this._rawData.Set("function", value); }
    }

    /// <summary>
    /// The type of the tool. Currently, only `function` is supported.
    /// </summary>
    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <summary>
    /// Opaque signature for thought continuity in multi-turn tool use (Google-specific,
    /// base64 encoded)
    /// </summary>
    public string? ThoughtSignature
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("thought_signature");
        }
        init { this._rawData.Set("thought_signature", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        this.Function.Validate();
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("function")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
        _ = this.ThoughtSignature;
    }

    public CompletionChatCompletionMessageToolCall()
    {
        this.Type = JsonSerializer.SerializeToElement("function");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public CompletionChatCompletionMessageToolCall(
        CompletionChatCompletionMessageToolCall completionChatCompletionMessageToolCall
    )
        : base(completionChatCompletionMessageToolCall) { }
#pragma warning restore CS8618

    public CompletionChatCompletionMessageToolCall(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("function");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    CompletionChatCompletionMessageToolCall(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="CompletionChatCompletionMessageToolCallFromRaw.FromRawUnchecked"/>
    public static CompletionChatCompletionMessageToolCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class CompletionChatCompletionMessageToolCallFromRaw
    : IFromRawJson<CompletionChatCompletionMessageToolCall>
{
    /// <inheritdoc/>
    public CompletionChatCompletionMessageToolCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => CompletionChatCompletionMessageToolCall.FromRawUnchecked(rawData);
}

/// <summary>
/// The function that the model called.
///
/// <para>Fields: - name (required): str - arguments (required): str</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Function, FunctionFromRaw>))]
public sealed record class Function : JsonModel
{
    /// <summary>
    /// The arguments to call the function with, as generated by the model in JSON
    /// format. Note that the model does not always generate valid JSON, and may hallucinate
    /// parameters not defined by your function schema. Validate the arguments in
    /// your code before calling your function.
    /// </summary>
    public required string Arguments
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("arguments");
        }
        init { this._rawData.Set("arguments", value); }
    }

    /// <summary>
    /// The name of the function to call.
    /// </summary>
    public required string Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("name");
        }
        init { this._rawData.Set("name", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Arguments;
        _ = this.Name;
    }

    public Function() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Function(Function function)
        : base(function) { }
#pragma warning restore CS8618

    public Function(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Function(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="FunctionFromRaw.FromRawUnchecked"/>
    public static Function FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class FunctionFromRaw : IFromRawJson<Function>
{
    /// <inheritdoc/>
    public Function FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Function.FromRawUnchecked(rawData);
}
