using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;
using System = System;

namespace DedalusSdk.Models.Chat.Completions;

/// <summary>
/// Schema for ChatCompletionStreamResponseChoicesItem.
///
/// <para>Fields: - delta (required): ChatCompletionStreamResponseDelta - logprobs
/// (optional): ChatCompletionStreamResponseChoicesItemLogprobs - finish_reason (required):
/// Literal["stop", "length", "tool_calls", "content_filter", "function_call"] -
/// index (required): int</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<StreamChoice, StreamChoiceFromRaw>))]
public sealed record class StreamChoice : JsonModel
{
    /// <summary>
    /// A chat completion delta generated by streamed model responses.
    /// </summary>
    public required ChoiceDelta Delta
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ChoiceDelta>("delta");
        }
        init { this._rawData.Set("delta", value); }
    }

    /// <summary>
    /// The reason the model stopped generating tokens. This will be `stop` if the
    /// model hit a natural stop point or a provided stop sequence, `length` if the
    /// maximum number of tokens specified in the request was reached, `content_filter`
    /// if content was omitted due to a flag from our content filters, `tool_calls`
    /// if the model called a tool, or `function_call` (deprecated) if the model called
    /// a function.
    /// </summary>
    public required ApiEnum<string, StreamChoiceFinishReason>? FinishReason
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, StreamChoiceFinishReason>>(
                "finish_reason"
            );
        }
        init { this._rawData.Set("finish_reason", value); }
    }

    /// <summary>
    /// The index of the choice in the list of choices.
    /// </summary>
    public required long Index
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("index");
        }
        init { this._rawData.Set("index", value); }
    }

    /// <summary>
    /// Log probability information for the choice.
    ///
    /// <para>Fields: - content (required): list[ChatCompletionTokenLogprob] - refusal
    /// (required): list[ChatCompletionTokenLogprob]</para>
    /// </summary>
    public StreamChoiceLogprobs? Logprobs
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<StreamChoiceLogprobs>("logprobs");
        }
        init { this._rawData.Set("logprobs", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        this.Delta.Validate();
        this.FinishReason?.Validate();
        _ = this.Index;
        this.Logprobs?.Validate();
    }

    public StreamChoice() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public StreamChoice(StreamChoice streamChoice)
        : base(streamChoice) { }
#pragma warning restore CS8618

    public StreamChoice(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    StreamChoice(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="StreamChoiceFromRaw.FromRawUnchecked"/>
    public static StreamChoice FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class StreamChoiceFromRaw : IFromRawJson<StreamChoice>
{
    /// <inheritdoc/>
    public StreamChoice FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        StreamChoice.FromRawUnchecked(rawData);
}

/// <summary>
/// The reason the model stopped generating tokens. This will be `stop` if the model
/// hit a natural stop point or a provided stop sequence, `length` if the maximum
/// number of tokens specified in the request was reached, `content_filter` if content
/// was omitted due to a flag from our content filters, `tool_calls` if the model
/// called a tool, or `function_call` (deprecated) if the model called a function.
/// </summary>
[JsonConverter(typeof(StreamChoiceFinishReasonConverter))]
public enum StreamChoiceFinishReason
{
    Stop,
    Length,
    ToolCalls,
    ContentFilter,
    FunctionCall,
}

sealed class StreamChoiceFinishReasonConverter : JsonConverter<StreamChoiceFinishReason>
{
    public override StreamChoiceFinishReason Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "stop" => StreamChoiceFinishReason.Stop,
            "length" => StreamChoiceFinishReason.Length,
            "tool_calls" => StreamChoiceFinishReason.ToolCalls,
            "content_filter" => StreamChoiceFinishReason.ContentFilter,
            "function_call" => StreamChoiceFinishReason.FunctionCall,
            _ => (StreamChoiceFinishReason)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        StreamChoiceFinishReason value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                StreamChoiceFinishReason.Stop => "stop",
                StreamChoiceFinishReason.Length => "length",
                StreamChoiceFinishReason.ToolCalls => "tool_calls",
                StreamChoiceFinishReason.ContentFilter => "content_filter",
                StreamChoiceFinishReason.FunctionCall => "function_call",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
