using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;

namespace DedalusSdk.Models.Images;

/// <summary>
/// Request to generate images.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<CreateImageRequest, CreateImageRequestFromRaw>))]
public sealed record class CreateImageRequest : JsonModel
{
    /// <summary>
    /// A text description of the desired image(s). The maximum length is 32000 characters
    /// for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
    /// </summary>
    public required string Prompt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("prompt");
        }
        init { this._rawData.Set("prompt", value); }
    }

    /// <summary>
    /// Allows to set transparency for the background of the generated image(s). This
    /// parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
    /// `opaque` or `auto` (default value). When `auto` is used, the model will automatically
    /// determine the best background for the image.
    ///
    /// <para>If `transparent`, the output format needs to support transparency, so
    /// it should be set to either `png` (default value) or `webp`.</para>
    /// </summary>
    public ApiEnum<string, CreateImageRequestBackground>? Background
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, CreateImageRequestBackground>>(
                "background"
            );
        }
        init { this._rawData.Set("background", value); }
    }

    /// <summary>
    /// The model to use for image generation. One of `openai/dall-e-2`, `openai/dall-e-3`,
    /// or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless a parameter
    /// specific to `gpt-image-1` is used.
    /// </summary>
    public string? Model
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("model");
        }
        init { this._rawData.Set("model", value); }
    }

    /// <summary>
    /// Control the content-moderation level for images generated by `gpt-image-1`.
    /// Must be either `low` for less restrictive filtering or `auto` (default value).
    /// </summary>
    public ApiEnum<string, CreateImageRequestModeration>? Moderation
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, CreateImageRequestModeration>>(
                "moderation"
            );
        }
        init { this._rawData.Set("moderation", value); }
    }

    /// <summary>
    /// The number of images to generate. Must be between 1 and 10. For `dall-e-3`,
    /// only `n=1` is supported.
    /// </summary>
    public long? N
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("n");
        }
        init { this._rawData.Set("n", value); }
    }

    /// <summary>
    /// The compression level (0-100%) for the generated images. This parameter is
    /// only supported for `gpt-image-1` with the `webp` or `jpeg` output formats,
    /// and defaults to 100.
    /// </summary>
    public long? OutputCompression
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("output_compression");
        }
        init { this._rawData.Set("output_compression", value); }
    }

    /// <summary>
    /// The format in which the generated images are returned. This parameter is
    /// only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
    /// </summary>
    public ApiEnum<string, CreateImageRequestOutputFormat>? OutputFormat
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, CreateImageRequestOutputFormat>>(
                "output_format"
            );
        }
        init { this._rawData.Set("output_format", value); }
    }

    /// <summary>
    /// The number of partial images to generate. This parameter is used for streaming
    /// responses that return partial images. Value must be between 0 and 3. When
    /// set to 0, the response will be a single image sent in one streaming event.
    ///
    /// <para>Note that the final image may be sent before the full number of partial
    /// images are generated if the full image is generated more quickly.</para>
    /// </summary>
    public long? PartialImages
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("partial_images");
        }
        init { this._rawData.Set("partial_images", value); }
    }

    /// <summary>
    /// The quality of the image that will be generated.
    ///
    /// <para>- `auto` (default value) will automatically select the best quality
    /// for the given model. - `high`, `medium` and `low` are supported for `gpt-image-1`.
    /// - `hd` and `standard` are supported for `dall-e-3`. - `standard` is the only
    /// option for `dall-e-2`.</para>
    /// </summary>
    public ApiEnum<string, CreateImageRequestQuality>? Quality
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, CreateImageRequestQuality>>(
                "quality"
            );
        }
        init { this._rawData.Set("quality", value); }
    }

    /// <summary>
    /// The format in which generated images with `dall-e-2` and `dall-e-3` are returned.
    /// Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after
    /// the image has been generated. This parameter isn't supported for `gpt-image-1`
    /// which will always return base64-encoded images.
    /// </summary>
    public ApiEnum<string, CreateImageRequestResponseFormat>? ResponseFormat
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<
                ApiEnum<string, CreateImageRequestResponseFormat>
            >("response_format");
        }
        init { this._rawData.Set("response_format", value); }
    }

    /// <summary>
    /// The size of the generated images. Must be one of `1024x1024`, `1536x1024`
    /// (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`,
    /// one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`,
    /// `1792x1024`, or `1024x1792` for `dall-e-3`.
    /// </summary>
    public ApiEnum<string, CreateImageRequestSize>? Size
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, CreateImageRequestSize>>("size");
        }
        init { this._rawData.Set("size", value); }
    }

    /// <summary>
    /// Generate the image in streaming mode. Defaults to `false`. See the [Image
    /// generation guide](https://platform.openai.com/docs/guides/image-generation)
    /// for more information. This parameter is only supported for `gpt-image-1`.
    /// </summary>
    public bool? Stream
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>("stream");
        }
        init { this._rawData.Set("stream", value); }
    }

    /// <summary>
    /// The style of the generated images. This parameter is only supported for `dall-e-3`.
    /// Must be one of `vivid` or `natural`. Vivid causes the model to lean towards
    /// generating hyper-real and dramatic images. Natural causes the model to produce
    /// more natural, less hyper-real looking images.
    /// </summary>
    public ApiEnum<string, CreateImageRequestStyle>? Style
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, CreateImageRequestStyle>>(
                "style"
            );
        }
        init { this._rawData.Set("style", value); }
    }

    /// <summary>
    /// A unique identifier representing your end-user, which can help OpenAI to monitor
    /// and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
    /// </summary>
    public string? User
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("user");
        }
        init { this._rawData.Set("user", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Prompt;
        this.Background?.Validate();
        _ = this.Model;
        this.Moderation?.Validate();
        _ = this.N;
        _ = this.OutputCompression;
        this.OutputFormat?.Validate();
        _ = this.PartialImages;
        this.Quality?.Validate();
        this.ResponseFormat?.Validate();
        this.Size?.Validate();
        _ = this.Stream;
        this.Style?.Validate();
        _ = this.User;
    }

    public CreateImageRequest() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public CreateImageRequest(CreateImageRequest createImageRequest)
        : base(createImageRequest) { }
#pragma warning restore CS8618

    public CreateImageRequest(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    CreateImageRequest(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="CreateImageRequestFromRaw.FromRawUnchecked"/>
    public static CreateImageRequest FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public CreateImageRequest(string prompt)
        : this()
    {
        this.Prompt = prompt;
    }
}

class CreateImageRequestFromRaw : IFromRawJson<CreateImageRequest>
{
    /// <inheritdoc/>
    public CreateImageRequest FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        CreateImageRequest.FromRawUnchecked(rawData);
}

/// <summary>
/// Allows to set transparency for the background of the generated image(s). This
/// parameter is only supported for `gpt-image-1`. Must be one of `transparent`, `opaque`
/// or `auto` (default value). When `auto` is used, the model will automatically
/// determine the best background for the image.
///
/// <para>If `transparent`, the output format needs to support transparency, so it
/// should be set to either `png` (default value) or `webp`.</para>
/// </summary>
[JsonConverter(typeof(CreateImageRequestBackgroundConverter))]
public enum CreateImageRequestBackground
{
    Transparent,
    Opaque,
    Auto,
}

sealed class CreateImageRequestBackgroundConverter : JsonConverter<CreateImageRequestBackground>
{
    public override CreateImageRequestBackground Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "transparent" => CreateImageRequestBackground.Transparent,
            "opaque" => CreateImageRequestBackground.Opaque,
            "auto" => CreateImageRequestBackground.Auto,
            _ => (CreateImageRequestBackground)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CreateImageRequestBackground value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CreateImageRequestBackground.Transparent => "transparent",
                CreateImageRequestBackground.Opaque => "opaque",
                CreateImageRequestBackground.Auto => "auto",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// Control the content-moderation level for images generated by `gpt-image-1`. Must
/// be either `low` for less restrictive filtering or `auto` (default value).
/// </summary>
[JsonConverter(typeof(CreateImageRequestModerationConverter))]
public enum CreateImageRequestModeration
{
    Low,
    Auto,
}

sealed class CreateImageRequestModerationConverter : JsonConverter<CreateImageRequestModeration>
{
    public override CreateImageRequestModeration Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "low" => CreateImageRequestModeration.Low,
            "auto" => CreateImageRequestModeration.Auto,
            _ => (CreateImageRequestModeration)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CreateImageRequestModeration value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CreateImageRequestModeration.Low => "low",
                CreateImageRequestModeration.Auto => "auto",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The format in which the generated images are returned. This parameter is only
/// supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
/// </summary>
[JsonConverter(typeof(CreateImageRequestOutputFormatConverter))]
public enum CreateImageRequestOutputFormat
{
    Png,
    Jpeg,
    Webp,
}

sealed class CreateImageRequestOutputFormatConverter : JsonConverter<CreateImageRequestOutputFormat>
{
    public override CreateImageRequestOutputFormat Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "png" => CreateImageRequestOutputFormat.Png,
            "jpeg" => CreateImageRequestOutputFormat.Jpeg,
            "webp" => CreateImageRequestOutputFormat.Webp,
            _ => (CreateImageRequestOutputFormat)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CreateImageRequestOutputFormat value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CreateImageRequestOutputFormat.Png => "png",
                CreateImageRequestOutputFormat.Jpeg => "jpeg",
                CreateImageRequestOutputFormat.Webp => "webp",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The quality of the image that will be generated.
///
/// <para>- `auto` (default value) will automatically select the best quality for
/// the given model. - `high`, `medium` and `low` are supported for `gpt-image-1`.
/// - `hd` and `standard` are supported for `dall-e-3`. - `standard` is the only
/// option for `dall-e-2`.</para>
/// </summary>
[JsonConverter(typeof(CreateImageRequestQualityConverter))]
public enum CreateImageRequestQuality
{
    Auto,
    High,
    Medium,
    Low,
    HD,
    Standard,
}

sealed class CreateImageRequestQualityConverter : JsonConverter<CreateImageRequestQuality>
{
    public override CreateImageRequestQuality Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "auto" => CreateImageRequestQuality.Auto,
            "high" => CreateImageRequestQuality.High,
            "medium" => CreateImageRequestQuality.Medium,
            "low" => CreateImageRequestQuality.Low,
            "hd" => CreateImageRequestQuality.HD,
            "standard" => CreateImageRequestQuality.Standard,
            _ => (CreateImageRequestQuality)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CreateImageRequestQuality value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CreateImageRequestQuality.Auto => "auto",
                CreateImageRequestQuality.High => "high",
                CreateImageRequestQuality.Medium => "medium",
                CreateImageRequestQuality.Low => "low",
                CreateImageRequestQuality.HD => "hd",
                CreateImageRequestQuality.Standard => "standard",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The format in which generated images with `dall-e-2` and `dall-e-3` are returned.
/// Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the
/// image has been generated. This parameter isn't supported for `gpt-image-1` which
/// will always return base64-encoded images.
/// </summary>
[JsonConverter(typeof(CreateImageRequestResponseFormatConverter))]
public enum CreateImageRequestResponseFormat
{
    Url,
    B64Json,
}

sealed class CreateImageRequestResponseFormatConverter
    : JsonConverter<CreateImageRequestResponseFormat>
{
    public override CreateImageRequestResponseFormat Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "url" => CreateImageRequestResponseFormat.Url,
            "b64_json" => CreateImageRequestResponseFormat.B64Json,
            _ => (CreateImageRequestResponseFormat)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CreateImageRequestResponseFormat value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CreateImageRequestResponseFormat.Url => "url",
                CreateImageRequestResponseFormat.B64Json => "b64_json",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape),
/// `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`,
/// `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`,
/// or `1024x1792` for `dall-e-3`.
/// </summary>
[JsonConverter(typeof(CreateImageRequestSizeConverter))]
public enum CreateImageRequestSize
{
    V256x256,
    V512x512,
    V1024x1024,
    V1536x1024,
    V1024x1536,
    V1792x1024,
    V1024x1792,
    Auto,
}

sealed class CreateImageRequestSizeConverter : JsonConverter<CreateImageRequestSize>
{
    public override CreateImageRequestSize Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "256x256" => CreateImageRequestSize.V256x256,
            "512x512" => CreateImageRequestSize.V512x512,
            "1024x1024" => CreateImageRequestSize.V1024x1024,
            "1536x1024" => CreateImageRequestSize.V1536x1024,
            "1024x1536" => CreateImageRequestSize.V1024x1536,
            "1792x1024" => CreateImageRequestSize.V1792x1024,
            "1024x1792" => CreateImageRequestSize.V1024x1792,
            "auto" => CreateImageRequestSize.Auto,
            _ => (CreateImageRequestSize)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CreateImageRequestSize value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CreateImageRequestSize.V256x256 => "256x256",
                CreateImageRequestSize.V512x512 => "512x512",
                CreateImageRequestSize.V1024x1024 => "1024x1024",
                CreateImageRequestSize.V1536x1024 => "1536x1024",
                CreateImageRequestSize.V1024x1536 => "1024x1536",
                CreateImageRequestSize.V1792x1024 => "1792x1024",
                CreateImageRequestSize.V1024x1792 => "1024x1792",
                CreateImageRequestSize.Auto => "auto",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The style of the generated images. This parameter is only supported for `dall-e-3`.
/// Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating
/// hyper-real and dramatic images. Natural causes the model to produce more natural,
/// less hyper-real looking images.
/// </summary>
[JsonConverter(typeof(CreateImageRequestStyleConverter))]
public enum CreateImageRequestStyle
{
    Vivid,
    Natural,
}

sealed class CreateImageRequestStyleConverter : JsonConverter<CreateImageRequestStyle>
{
    public override CreateImageRequestStyle Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "vivid" => CreateImageRequestStyle.Vivid,
            "natural" => CreateImageRequestStyle.Natural,
            _ => (CreateImageRequestStyle)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CreateImageRequestStyle value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CreateImageRequestStyle.Vivid => "vivid",
                CreateImageRequestStyle.Natural => "natural",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
