using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;

namespace DedalusSdk.Models.Images;

/// <summary>
/// Generate images from text prompts.
///
/// <para>Pure image generation models only (DALL-E, GPT Image). For multimodal models
/// like gemini-2.5-flash-image, use /v1/chat/completions.</para>
///
/// <para>NOTE: Do not inherit from this type outside the SDK unless you're okay with
/// breaking changes in non-major versions. We may add new methods in the future that
/// cause existing derived classes to break.</para>
/// </summary>
public record class ImageGenerateParams : ParamsBase
{
    readonly JsonDictionary _rawBodyData = new();
    public IReadOnlyDictionary<string, JsonElement> RawBodyData
    {
        get { return this._rawBodyData.Freeze(); }
    }

    /// <summary>
    /// A text description of the desired image(s). The maximum length is 32000 characters
    /// for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
    /// </summary>
    public required string Prompt
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>("prompt");
        }
        init { this._rawBodyData.Set("prompt", value); }
    }

    /// <summary>
    /// Allows to set transparency for the background of the generated image(s). This
    /// parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
    /// `opaque` or `auto` (default value). When `auto` is used, the model will automatically
    /// determine the best background for the image.
    ///
    /// <para>If `transparent`, the output format needs to support transparency, so
    /// it should be set to either `png` (default value) or `webp`.</para>
    /// </summary>
    public ApiEnum<string, Background>? Background
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<ApiEnum<string, Background>>("background");
        }
        init { this._rawBodyData.Set("background", value); }
    }

    /// <summary>
    /// The model to use for image generation. One of `openai/dall-e-2`, `openai/dall-e-3`,
    /// or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless a parameter
    /// specific to `gpt-image-1` is used.
    /// </summary>
    public string? Model
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>("model");
        }
        init { this._rawBodyData.Set("model", value); }
    }

    /// <summary>
    /// Control the content-moderation level for images generated by `gpt-image-1`.
    /// Must be either `low` for less restrictive filtering or `auto` (default value).
    /// </summary>
    public ApiEnum<string, Moderation>? Moderation
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<ApiEnum<string, Moderation>>("moderation");
        }
        init { this._rawBodyData.Set("moderation", value); }
    }

    /// <summary>
    /// The number of images to generate. Must be between 1 and 10. For `dall-e-3`,
    /// only `n=1` is supported.
    /// </summary>
    public long? N
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<long>("n");
        }
        init { this._rawBodyData.Set("n", value); }
    }

    /// <summary>
    /// The compression level (0-100%) for the generated images. This parameter is
    /// only supported for `gpt-image-1` with the `webp` or `jpeg` output formats,
    /// and defaults to 100.
    /// </summary>
    public long? OutputCompression
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<long>("output_compression");
        }
        init { this._rawBodyData.Set("output_compression", value); }
    }

    /// <summary>
    /// The format in which the generated images are returned. This parameter is
    /// only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
    /// </summary>
    public ApiEnum<string, OutputFormat>? OutputFormat
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<ApiEnum<string, OutputFormat>>(
                "output_format"
            );
        }
        init { this._rawBodyData.Set("output_format", value); }
    }

    /// <summary>
    /// The number of partial images to generate. This parameter is used for streaming
    /// responses that return partial images. Value must be between 0 and 3. When
    /// set to 0, the response will be a single image sent in one streaming event.
    ///
    /// <para>Note that the final image may be sent before the full number of partial
    /// images are generated if the full image is generated more quickly.</para>
    /// </summary>
    public long? PartialImages
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<long>("partial_images");
        }
        init { this._rawBodyData.Set("partial_images", value); }
    }

    /// <summary>
    /// The quality of the image that will be generated.
    ///
    /// <para>- `auto` (default value) will automatically select the best quality
    /// for the given model. - `high`, `medium` and `low` are supported for `gpt-image-1`.
    /// - `hd` and `standard` are supported for `dall-e-3`. - `standard` is the only
    /// option for `dall-e-2`.</para>
    /// </summary>
    public ApiEnum<string, Quality>? Quality
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<ApiEnum<string, Quality>>("quality");
        }
        init { this._rawBodyData.Set("quality", value); }
    }

    /// <summary>
    /// The format in which generated images with `dall-e-2` and `dall-e-3` are returned.
    /// Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after
    /// the image has been generated. This parameter isn't supported for `gpt-image-1`
    /// which will always return base64-encoded images.
    /// </summary>
    public ApiEnum<string, ResponseFormat>? ResponseFormat
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<ApiEnum<string, ResponseFormat>>(
                "response_format"
            );
        }
        init { this._rawBodyData.Set("response_format", value); }
    }

    /// <summary>
    /// The size of the generated images. Must be one of `1024x1024`, `1536x1024`
    /// (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`,
    /// one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`,
    /// `1792x1024`, or `1024x1792` for `dall-e-3`.
    /// </summary>
    public ApiEnum<string, Size>? Size
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<ApiEnum<string, Size>>("size");
        }
        init { this._rawBodyData.Set("size", value); }
    }

    /// <summary>
    /// Generate the image in streaming mode. Defaults to `false`. See the [Image
    /// generation guide](https://platform.openai.com/docs/guides/image-generation)
    /// for more information. This parameter is only supported for `gpt-image-1`.
    /// </summary>
    public bool? Stream
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>("stream");
        }
        init { this._rawBodyData.Set("stream", value); }
    }

    /// <summary>
    /// The style of the generated images. This parameter is only supported for `dall-e-3`.
    /// Must be one of `vivid` or `natural`. Vivid causes the model to lean towards
    /// generating hyper-real and dramatic images. Natural causes the model to produce
    /// more natural, less hyper-real looking images.
    /// </summary>
    public ApiEnum<string, Style>? Style
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<ApiEnum<string, Style>>("style");
        }
        init { this._rawBodyData.Set("style", value); }
    }

    /// <summary>
    /// A unique identifier representing your end-user, which can help OpenAI to monitor
    /// and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
    /// </summary>
    public string? User
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>("user");
        }
        init { this._rawBodyData.Set("user", value); }
    }

    public ImageGenerateParams() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ImageGenerateParams(ImageGenerateParams imageGenerateParams)
        : base(imageGenerateParams)
    {
        this._rawBodyData = new(imageGenerateParams._rawBodyData);
    }
#pragma warning restore CS8618

    public ImageGenerateParams(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ImageGenerateParams(
        FrozenDictionary<string, JsonElement> rawHeaderData,
        FrozenDictionary<string, JsonElement> rawQueryData,
        FrozenDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="IFromRawJson{T}.FromRawUnchecked"/>
    public static ImageGenerateParams FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        return new(
            FrozenDictionary.ToFrozenDictionary(rawHeaderData),
            FrozenDictionary.ToFrozenDictionary(rawQueryData),
            FrozenDictionary.ToFrozenDictionary(rawBodyData)
        );
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(
                new Dictionary<string, JsonElement>()
                {
                    ["HeaderData"] = FriendlyJsonPrinter.PrintValue(
                        JsonSerializer.SerializeToElement(this._rawHeaderData.Freeze())
                    ),
                    ["QueryData"] = FriendlyJsonPrinter.PrintValue(
                        JsonSerializer.SerializeToElement(this._rawQueryData.Freeze())
                    ),
                    ["BodyData"] = FriendlyJsonPrinter.PrintValue(this._rawBodyData.Freeze()),
                }
            ),
            ModelBase.ToStringSerializerOptions
        );

    public virtual bool Equals(ImageGenerateParams? other)
    {
        if (other == null)
        {
            return false;
        }
        return this._rawHeaderData.Equals(other._rawHeaderData)
            && this._rawQueryData.Equals(other._rawQueryData)
            && this._rawBodyData.Equals(other._rawBodyData);
    }

    public override Uri Url(ClientOptions options)
    {
        return new UriBuilder(options.BaseUrl.ToString().TrimEnd('/') + "/v1/images/generations")
        {
            Query = this.QueryString(options),
        }.Uri;
    }

    internal override HttpContent? BodyContent()
    {
        return new StringContent(
            JsonSerializer.Serialize(this.RawBodyData, ModelBase.SerializerOptions),
            Encoding.UTF8,
            "application/json"
        );
    }

    internal override void AddHeadersToRequest(HttpRequestMessage request, ClientOptions options)
    {
        ParamsBase.AddDefaultHeaders(request, options);
        foreach (var item in this.RawHeaderData)
        {
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }

    public override int GetHashCode()
    {
        return 0;
    }
}

/// <summary>
/// Allows to set transparency for the background of the generated image(s). This
/// parameter is only supported for `gpt-image-1`. Must be one of `transparent`, `opaque`
/// or `auto` (default value). When `auto` is used, the model will automatically
/// determine the best background for the image.
///
/// <para>If `transparent`, the output format needs to support transparency, so it
/// should be set to either `png` (default value) or `webp`.</para>
/// </summary>
[JsonConverter(typeof(BackgroundConverter))]
public enum Background
{
    Transparent,
    Opaque,
    Auto,
}

sealed class BackgroundConverter : JsonConverter<Background>
{
    public override Background Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "transparent" => Background.Transparent,
            "opaque" => Background.Opaque,
            "auto" => Background.Auto,
            _ => (Background)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        Background value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Background.Transparent => "transparent",
                Background.Opaque => "opaque",
                Background.Auto => "auto",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// Control the content-moderation level for images generated by `gpt-image-1`. Must
/// be either `low` for less restrictive filtering or `auto` (default value).
/// </summary>
[JsonConverter(typeof(ModerationConverter))]
public enum Moderation
{
    Low,
    Auto,
}

sealed class ModerationConverter : JsonConverter<Moderation>
{
    public override Moderation Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "low" => Moderation.Low,
            "auto" => Moderation.Auto,
            _ => (Moderation)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        Moderation value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Moderation.Low => "low",
                Moderation.Auto => "auto",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The format in which the generated images are returned. This parameter is only
/// supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
/// </summary>
[JsonConverter(typeof(OutputFormatConverter))]
public enum OutputFormat
{
    Png,
    Jpeg,
    Webp,
}

sealed class OutputFormatConverter : JsonConverter<OutputFormat>
{
    public override OutputFormat Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "png" => OutputFormat.Png,
            "jpeg" => OutputFormat.Jpeg,
            "webp" => OutputFormat.Webp,
            _ => (OutputFormat)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        OutputFormat value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                OutputFormat.Png => "png",
                OutputFormat.Jpeg => "jpeg",
                OutputFormat.Webp => "webp",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The quality of the image that will be generated.
///
/// <para>- `auto` (default value) will automatically select the best quality for
/// the given model. - `high`, `medium` and `low` are supported for `gpt-image-1`.
/// - `hd` and `standard` are supported for `dall-e-3`. - `standard` is the only
/// option for `dall-e-2`.</para>
/// </summary>
[JsonConverter(typeof(QualityConverter))]
public enum Quality
{
    Auto,
    High,
    Medium,
    Low,
    HD,
    Standard,
}

sealed class QualityConverter : JsonConverter<Quality>
{
    public override Quality Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "auto" => Quality.Auto,
            "high" => Quality.High,
            "medium" => Quality.Medium,
            "low" => Quality.Low,
            "hd" => Quality.HD,
            "standard" => Quality.Standard,
            _ => (Quality)(-1),
        };
    }

    public override void Write(Utf8JsonWriter writer, Quality value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Quality.Auto => "auto",
                Quality.High => "high",
                Quality.Medium => "medium",
                Quality.Low => "low",
                Quality.HD => "hd",
                Quality.Standard => "standard",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The format in which generated images with `dall-e-2` and `dall-e-3` are returned.
/// Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the
/// image has been generated. This parameter isn't supported for `gpt-image-1` which
/// will always return base64-encoded images.
/// </summary>
[JsonConverter(typeof(ResponseFormatConverter))]
public enum ResponseFormat
{
    Url,
    B64Json,
}

sealed class ResponseFormatConverter : JsonConverter<ResponseFormat>
{
    public override ResponseFormat Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "url" => ResponseFormat.Url,
            "b64_json" => ResponseFormat.B64Json,
            _ => (ResponseFormat)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        ResponseFormat value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                ResponseFormat.Url => "url",
                ResponseFormat.B64Json => "b64_json",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape),
/// `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`,
/// `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`,
/// or `1024x1792` for `dall-e-3`.
/// </summary>
[JsonConverter(typeof(SizeConverter))]
public enum Size
{
    V256x256,
    V512x512,
    V1024x1024,
    V1536x1024,
    V1024x1536,
    V1792x1024,
    V1024x1792,
    Auto,
}

sealed class SizeConverter : JsonConverter<Size>
{
    public override Size Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "256x256" => Size.V256x256,
            "512x512" => Size.V512x512,
            "1024x1024" => Size.V1024x1024,
            "1536x1024" => Size.V1536x1024,
            "1024x1536" => Size.V1024x1536,
            "1792x1024" => Size.V1792x1024,
            "1024x1792" => Size.V1024x1792,
            "auto" => Size.Auto,
            _ => (Size)(-1),
        };
    }

    public override void Write(Utf8JsonWriter writer, Size value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Size.V256x256 => "256x256",
                Size.V512x512 => "512x512",
                Size.V1024x1024 => "1024x1024",
                Size.V1536x1024 => "1536x1024",
                Size.V1024x1536 => "1024x1536",
                Size.V1792x1024 => "1792x1024",
                Size.V1024x1792 => "1024x1792",
                Size.Auto => "auto",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// The style of the generated images. This parameter is only supported for `dall-e-3`.
/// Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating
/// hyper-real and dramatic images. Natural causes the model to produce more natural,
/// less hyper-real looking images.
/// </summary>
[JsonConverter(typeof(StyleConverter))]
public enum Style
{
    Vivid,
    Natural,
}

sealed class StyleConverter : JsonConverter<Style>
{
    public override Style Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "vivid" => Style.Vivid,
            "natural" => Style.Natural,
            _ => (Style)(-1),
        };
    }

    public override void Write(Utf8JsonWriter writer, Style value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Style.Vivid => "vivid",
                Style.Natural => "natural",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
