using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;

namespace DedalusSdk.Models.Embeddings;

/// <summary>
/// Schema for EmbeddingResponse.
///
/// <para>Fields: - data (required): list[Embedding] - model (required): str - object
/// (required): Literal["list"] - usage (required): Usage</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<CreateEmbeddingResponse, CreateEmbeddingResponseFromRaw>))]
public sealed record class CreateEmbeddingResponse : JsonModel
{
    /// <summary>
    /// The list of embeddings generated by the model.
    /// </summary>
    public required IReadOnlyList<Data> Data
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<ImmutableArray<Data>>("data");
        }
        init
        {
            this._rawData.Set<ImmutableArray<Data>>("data", ImmutableArray.ToImmutableArray(value));
        }
    }

    /// <summary>
    /// The name of the model used to generate the embedding.
    /// </summary>
    public required string Model
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("model");
        }
        init { this._rawData.Set("model", value); }
    }

    /// <summary>
    /// The object type, which is always "list".
    /// </summary>
    public JsonElement Object
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("object");
        }
        init { this._rawData.Set("object", value); }
    }

    /// <summary>
    /// The usage information for the request.
    /// </summary>
    public required Usage Usage
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<Usage>("usage");
        }
        init { this._rawData.Set("usage", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        foreach (var item in this.Data)
        {
            item.Validate();
        }
        _ = this.Model;
        if (!JsonElement.DeepEquals(this.Object, JsonSerializer.SerializeToElement("list")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
        this.Usage.Validate();
    }

    public CreateEmbeddingResponse()
    {
        this.Object = JsonSerializer.SerializeToElement("list");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public CreateEmbeddingResponse(CreateEmbeddingResponse createEmbeddingResponse)
        : base(createEmbeddingResponse) { }
#pragma warning restore CS8618

    public CreateEmbeddingResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Object = JsonSerializer.SerializeToElement("list");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    CreateEmbeddingResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="CreateEmbeddingResponseFromRaw.FromRawUnchecked"/>
    public static CreateEmbeddingResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class CreateEmbeddingResponseFromRaw : IFromRawJson<CreateEmbeddingResponse>
{
    /// <inheritdoc/>
    public CreateEmbeddingResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => CreateEmbeddingResponse.FromRawUnchecked(rawData);
}

/// <summary>
/// Represents an embedding vector returned by embedding endpoint.
///
/// <para>Fields: - index (required): int - embedding (required): list[float] - object
/// (required): Literal["embedding"]</para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Data, DataFromRaw>))]
public sealed record class Data : JsonModel
{
    /// <summary>
    /// The embedding vector, which is a list of floats. The length of vector depends
    /// on the model as listed in the [embedding guide](/docs/guides/embeddings).
    /// </summary>
    public required IReadOnlyList<double> Embedding
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<ImmutableArray<double>>("embedding");
        }
        init
        {
            this._rawData.Set<ImmutableArray<double>>(
                "embedding",
                ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// The index of the embedding in the list of embeddings.
    /// </summary>
    public required long Index
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("index");
        }
        init { this._rawData.Set("index", value); }
    }

    /// <summary>
    /// The object type, which is always "embedding".
    /// </summary>
    public JsonElement Object
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("object");
        }
        init { this._rawData.Set("object", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Embedding;
        _ = this.Index;
        if (!JsonElement.DeepEquals(this.Object, JsonSerializer.SerializeToElement("embedding")))
        {
            throw new DedalusInvalidDataException("Invalid value given for constant");
        }
    }

    public Data()
    {
        this.Object = JsonSerializer.SerializeToElement("embedding");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Data(Data data)
        : base(data) { }
#pragma warning restore CS8618

    public Data(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Object = JsonSerializer.SerializeToElement("embedding");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Data(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="DataFromRaw.FromRawUnchecked"/>
    public static Data FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class DataFromRaw : IFromRawJson<Data>
{
    /// <inheritdoc/>
    public Data FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Data.FromRawUnchecked(rawData);
}

/// <summary>
/// The usage information for the request.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Usage, UsageFromRaw>))]
public sealed record class Usage : JsonModel
{
    /// <summary>
    /// The number of tokens used by the prompt.
    /// </summary>
    public required long PromptTokens
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("prompt_tokens");
        }
        init { this._rawData.Set("prompt_tokens", value); }
    }

    /// <summary>
    /// The total number of tokens used by the request.
    /// </summary>
    public required long TotalTokens
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("total_tokens");
        }
        init { this._rawData.Set("total_tokens", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.PromptTokens;
        _ = this.TotalTokens;
    }

    public Usage() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Usage(Usage usage)
        : base(usage) { }
#pragma warning restore CS8618

    public Usage(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Usage(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="UsageFromRaw.FromRawUnchecked"/>
    public static Usage FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class UsageFromRaw : IFromRawJson<Usage>
{
    /// <inheritdoc/>
    public Usage FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Usage.FromRawUnchecked(rawData);
}
