using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using DedalusSdk.Core;
using DedalusSdk.Exceptions;

namespace DedalusSdk.Models.Responses;

/// <summary>
/// Responses API response with Dedalus extensions.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Response, ResponseFromRaw>))]
public sealed record class Response : JsonModel
{
    /// <summary>
    /// Unique identifier for this Response
    /// </summary>
    public required string ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("id");
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// Unix timestamp (in seconds) when this Response was created
    /// </summary>
    public required double CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<double>("created_at");
        }
        init { this._rawData.Set("created_at", value); }
    }

    /// <summary>
    /// The model used for this response
    /// </summary>
    public required string Model
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("model");
        }
        init { this._rawData.Set("model", value); }
    }

    /// <summary>
    /// Array of content items generated by the model
    /// </summary>
    public required IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>> Output
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<
                ImmutableArray<FrozenDictionary<string, JsonValueInput?>>
            >("output");
        }
        init
        {
            this._rawData.Set<ImmutableArray<FrozenDictionary<string, JsonValueInput?>>>(
                "output",
                ImmutableArray.ToImmutableArray(
                    Enumerable.Select(value, (item) => FrozenDictionary.ToFrozenDictionary(item))
                )
            );
        }
    }

    /// <summary>
    /// The status of the response generation
    /// </summary>
    public required ApiEnum<string, Status> Status
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, Status>>("status");
        }
        init { this._rawData.Set("status", value); }
    }

    /// <summary>
    /// Whether the request was run in the background
    /// </summary>
    public bool? Background
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>("background");
        }
        init { this._rawData.Set("background", value); }
    }

    /// <summary>
    /// Unix timestamp (in seconds) when the response was completed
    /// </summary>
    public double? CompletedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("completed_at");
        }
        init { this._rawData.Set("completed_at", value); }
    }

    /// <summary>
    /// Conversation this response belongs to (requires BYOK)
    /// </summary>
    public IReadOnlyDictionary<string, JsonValueInput?>? Conversation
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, JsonValueInput?>>(
                "conversation"
            );
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, JsonValueInput?>?>(
                "conversation",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// Error details if status is 'failed'
    /// </summary>
    public IReadOnlyDictionary<string, JsonValueInput?>? Error
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, JsonValueInput?>>(
                "error"
            );
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, JsonValueInput?>?>(
                "error",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// Frequency penalty used for this response
    /// </summary>
    public double? FrequencyPenalty
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("frequency_penalty");
        }
        init { this._rawData.Set("frequency_penalty", value); }
    }

    /// <summary>
    /// Details about why the response is incomplete (e.g., max_output_tokens, content_filter)
    /// </summary>
    public IReadOnlyDictionary<string, string>? IncompleteDetails
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, string>>(
                "incomplete_details"
            );
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, string>?>(
                "incomplete_details",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// System/developer instructions used
    /// </summary>
    public ResponseInstructions? Instructions
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ResponseInstructions>("instructions");
        }
        init { this._rawData.Set("instructions", value); }
    }

    /// <summary>
    /// Maximum output tokens allowed for this response
    /// </summary>
    public long? MaxOutputTokens
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("max_output_tokens");
        }
        init { this._rawData.Set("max_output_tokens", value); }
    }

    /// <summary>
    /// Maximum tool calls allowed for this response
    /// </summary>
    public long? MaxToolCalls
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("max_tool_calls");
        }
        init { this._rawData.Set("max_tool_calls", value); }
    }

    /// <summary>
    /// MCP server failures keyed by server name.
    /// </summary>
    public IReadOnlyDictionary<string, McpServerErrorsItem>? McpServerErrors
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, McpServerErrorsItem>>(
                "mcp_server_errors"
            );
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, McpServerErrorsItem>?>(
                "mcp_server_errors",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// Results of MCP tool executions including inputs, outputs, and timing.
    /// </summary>
    public IReadOnlyList<McpToolResult>? McpToolResults
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<McpToolResult>>(
                "mcp_tool_results"
            );
        }
        init
        {
            this._rawData.Set<ImmutableArray<McpToolResult>?>(
                "mcp_tool_results",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Key-value pairs attached to this response (requires BYOK)
    /// </summary>
    public IReadOnlyDictionary<string, string>? Metadata
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, string>>("metadata");
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, string>?>(
                "metadata",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// The object type, always 'response'
    /// </summary>
    public ApiEnum<string, global::DedalusSdk.Models.Responses.Object>? Object
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<
                ApiEnum<string, global::DedalusSdk.Models.Responses.Object>
            >("object");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("object", value);
        }
    }

    /// <summary>
    /// Aggregated text output from all output_text items (SDK-only convenience property)
    /// </summary>
    public string? OutputText
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("output_text");
        }
        init { this._rawData.Set("output_text", value); }
    }

    /// <summary>
    /// Whether parallel tool calls were enabled
    /// </summary>
    public bool? ParallelToolCalls
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>("parallel_tool_calls");
        }
        init { this._rawData.Set("parallel_tool_calls", value); }
    }

    /// <summary>
    /// Presence penalty used for this response
    /// </summary>
    public double? PresencePenalty
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("presence_penalty");
        }
        init { this._rawData.Set("presence_penalty", value); }
    }

    /// <summary>
    /// Previous response ID referenced, if any
    /// </summary>
    public string? PreviousResponseID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("previous_response_id");
        }
        init { this._rawData.Set("previous_response_id", value); }
    }

    /// <summary>
    /// Prompt cache key used for this response
    /// </summary>
    public string? PromptCacheKey
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("prompt_cache_key");
        }
        init { this._rawData.Set("prompt_cache_key", value); }
    }

    /// <summary>
    /// Reasoning configuration and outputs
    /// </summary>
    public IReadOnlyDictionary<string, JsonValueInput?>? Reasoning
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, JsonValueInput?>>(
                "reasoning"
            );
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, JsonValueInput?>?>(
                "reasoning",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// Safety identifier used for this response
    /// </summary>
    public string? SafetyIdentifier
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("safety_identifier");
        }
        init { this._rawData.Set("safety_identifier", value); }
    }

    /// <summary>
    /// Service tier used for this response
    /// </summary>
    public string? ServiceTier
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("service_tier");
        }
        init { this._rawData.Set("service_tier", value); }
    }

    /// <summary>
    /// Whether the response was stored for later retrieval
    /// </summary>
    public bool? Store
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>("store");
        }
        init { this._rawData.Set("store", value); }
    }

    /// <summary>
    /// Temperature parameter used
    /// </summary>
    public double? Temperature
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("temperature");
        }
        init { this._rawData.Set("temperature", value); }
    }

    /// <summary>
    /// Text configuration used for this response
    /// </summary>
    public IReadOnlyDictionary<string, JsonValueInput?>? Text
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, JsonValueInput?>>(
                "text"
            );
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, JsonValueInput?>?>(
                "text",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// Tool choice configuration used
    /// </summary>
    public ResponseToolChoice? ToolChoice
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ResponseToolChoice>("tool_choice");
        }
        init { this._rawData.Set("tool_choice", value); }
    }

    /// <summary>
    /// Tools that were available to the model
    /// </summary>
    public IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>>? Tools
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<
                ImmutableArray<FrozenDictionary<string, JsonValueInput?>>
            >("tools");
        }
        init
        {
            this._rawData.Set<ImmutableArray<FrozenDictionary<string, JsonValueInput?>>?>(
                "tools",
                value == null
                    ? null
                    : ImmutableArray.ToImmutableArray(
                        Enumerable.Select(
                            value,
                            (item) => FrozenDictionary.ToFrozenDictionary(item)
                        )
                    )
            );
        }
    }

    /// <summary>
    /// List of tool names that were executed server-side (e.g., MCP tools).
    /// </summary>
    public IReadOnlyList<string>? ToolsExecuted
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<string>>("tools_executed");
        }
        init
        {
            this._rawData.Set<ImmutableArray<string>?>(
                "tools_executed",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Number of logprob tokens returned per position
    /// </summary>
    public long? TopLogprobs
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("top_logprobs");
        }
        init { this._rawData.Set("top_logprobs", value); }
    }

    /// <summary>
    /// Top-p parameter used
    /// </summary>
    public double? TopP
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("top_p");
        }
        init { this._rawData.Set("top_p", value); }
    }

    /// <summary>
    /// Truncation strategy applied when context exceeded limits
    /// </summary>
    public string? Truncation
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("truncation");
        }
        init { this._rawData.Set("truncation", value); }
    }

    /// <summary>
    /// Token usage statistics for the response
    /// </summary>
    public IReadOnlyDictionary<string, JsonValueInput?>? Usage
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, JsonValueInput?>>(
                "usage"
            );
        }
        init
        {
            this._rawData.Set<FrozenDictionary<string, JsonValueInput?>?>(
                "usage",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.CreatedAt;
        _ = this.Model;
        foreach (var item in this.Output)
        {
            foreach (var item1 in item.Values)
            {
                item1?.Validate();
            }
        }
        this.Status.Validate();
        _ = this.Background;
        _ = this.CompletedAt;
        if (this.Conversation != null)
        {
            foreach (var item in this.Conversation.Values)
            {
                item?.Validate();
            }
        }
        if (this.Error != null)
        {
            foreach (var item in this.Error.Values)
            {
                item?.Validate();
            }
        }
        _ = this.FrequencyPenalty;
        _ = this.IncompleteDetails;
        this.Instructions?.Validate();
        _ = this.MaxOutputTokens;
        _ = this.MaxToolCalls;
        if (this.McpServerErrors != null)
        {
            foreach (var item in this.McpServerErrors.Values)
            {
                item.Validate();
            }
        }
        foreach (var item in this.McpToolResults ?? [])
        {
            item.Validate();
        }
        _ = this.Metadata;
        this.Object?.Validate();
        _ = this.OutputText;
        _ = this.ParallelToolCalls;
        _ = this.PresencePenalty;
        _ = this.PreviousResponseID;
        _ = this.PromptCacheKey;
        if (this.Reasoning != null)
        {
            foreach (var item in this.Reasoning.Values)
            {
                item?.Validate();
            }
        }
        _ = this.SafetyIdentifier;
        _ = this.ServiceTier;
        _ = this.Store;
        _ = this.Temperature;
        if (this.Text != null)
        {
            foreach (var item in this.Text.Values)
            {
                item?.Validate();
            }
        }
        this.ToolChoice?.Validate();
        foreach (var item in this.Tools ?? [])
        {
            foreach (var item1 in item.Values)
            {
                item1?.Validate();
            }
        }
        _ = this.ToolsExecuted;
        _ = this.TopLogprobs;
        _ = this.TopP;
        _ = this.Truncation;
        if (this.Usage != null)
        {
            foreach (var item in this.Usage.Values)
            {
                item?.Validate();
            }
        }
    }

    public Response() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Response(Response response)
        : base(response) { }
#pragma warning restore CS8618

    public Response(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Response(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ResponseFromRaw.FromRawUnchecked"/>
    public static Response FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ResponseFromRaw : IFromRawJson<Response>
{
    /// <inheritdoc/>
    public Response FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Response.FromRawUnchecked(rawData);
}

/// <summary>
/// The status of the response generation
/// </summary>
[JsonConverter(typeof(StatusConverter))]
public enum Status
{
    Completed,
    Failed,
    InProgress,
    Cancelled,
    Queued,
    Incomplete,
}

sealed class StatusConverter : JsonConverter<Status>
{
    public override Status Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "completed" => Status.Completed,
            "failed" => Status.Failed,
            "in_progress" => Status.InProgress,
            "cancelled" => Status.Cancelled,
            "queued" => Status.Queued,
            "incomplete" => Status.Incomplete,
            _ => (Status)(-1),
        };
    }

    public override void Write(Utf8JsonWriter writer, Status value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Status.Completed => "completed",
                Status.Failed => "failed",
                Status.InProgress => "in_progress",
                Status.Cancelled => "cancelled",
                Status.Queued => "queued",
                Status.Incomplete => "incomplete",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// System/developer instructions used
/// </summary>
[JsonConverter(typeof(ResponseInstructionsConverter))]
public record class ResponseInstructions : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public ResponseInstructions(string value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public ResponseInstructions(
        IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>> value,
        JsonElement? element = null
    )
    {
        this.Value = ImmutableArray.ToImmutableArray(
            Enumerable.Select(value, (item) => FrozenDictionary.ToFrozenDictionary(item))
        );
        this._element = element;
    }

    public ResponseInstructions(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="string"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickString(out var value)) {
    ///     // `value` is of type `string`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickString([NotNullWhen(true)] out string? value)
    {
        value = this.Value as string;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="List{T}"/> where <c>T</c> is a <c>Dictionary&lt;string, JsonValueInput?&gt;</c>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickJsonValueInputs(out var value)) {
    ///     // `value` is of type `IReadOnlyList&lt;IReadOnlyDictionary&lt;string, JsonValueInput?&gt;&gt;`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickJsonValueInputs(
        [NotNullWhen(true)] out IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>>? value
    )
    {
        value = this.Value as IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>>;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (string value) =&gt; {...},
    ///     (IReadOnlyList&lt;IReadOnlyDictionary&lt;string, JsonValueInput?&gt;&gt; value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        Action<string> @string,
        Action<IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>>> jsonValueInputs
    )
    {
        switch (this.Value)
        {
            case string value:
                @string(value);
                break;
            case IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>> value:
                jsonValueInputs(value);
                break;
            default:
                throw new DedalusInvalidDataException(
                    "Data did not match any variant of ResponseInstructions"
                );
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (string value) =&gt; {...},
    ///     (IReadOnlyList&lt;IReadOnlyDictionary&lt;string, JsonValueInput?&gt;&gt; value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        Func<string, T> @string,
        Func<IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>>, T> jsonValueInputs
    )
    {
        return this.Value switch
        {
            string value => @string(value),
            IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>> value => jsonValueInputs(
                value
            ),
            _ => throw new DedalusInvalidDataException(
                "Data did not match any variant of ResponseInstructions"
            ),
        };
    }

    public static implicit operator ResponseInstructions(string value) => new(value);

    public static implicit operator ResponseInstructions(
        List<Dictionary<string, JsonValueInput?>> value
    ) => new((IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>>)value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new DedalusInvalidDataException(
                "Data did not match any variant of ResponseInstructions"
            );
        }
        this.Switch(
            (_) => { },
            (jsonValueInputs) =>
            {
                foreach (var item in jsonValueInputs)
                {
                    foreach (var item1 in item.Values)
                    {
                        item1?.Validate();
                    }
                }
            }
        );
    }

    public virtual bool Equals(ResponseInstructions? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            string _ => 0,
            IReadOnlyList<IReadOnlyDictionary<string, JsonValueInput?>> _ => 1,
            _ => -1,
        };
    }
}

sealed class ResponseInstructionsConverter : JsonConverter<ResponseInstructions?>
{
    public override ResponseInstructions? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        try
        {
            var deserialized = JsonSerializer.Deserialize<string>(element, options);
            if (deserialized != null)
            {
                return new(deserialized, element);
            }
        }
        catch (Exception e) when (e is JsonException || e is DedalusInvalidDataException)
        {
            // ignore
        }

        try
        {
            var deserialized = JsonSerializer.Deserialize<
                List<Dictionary<string, JsonValueInput?>>
            >(element, options);
            if (deserialized != null)
            {
                foreach (var item in deserialized)
                {
                    foreach (var item1 in item.Values)
                    {
                        item1?.Validate();
                    }
                }
                return new(deserialized, element);
            }
        }
        catch (Exception e) when (e is JsonException || e is DedalusInvalidDataException)
        {
            // ignore
        }

        return new(element);
    }

    public override void Write(
        Utf8JsonWriter writer,
        ResponseInstructions? value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value?.Json, options);
    }
}

/// <summary>
/// Error details for a single MCP server failure.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<McpServerErrorsItem, McpServerErrorsItemFromRaw>))]
public sealed record class McpServerErrorsItem : JsonModel
{
    /// <summary>
    /// Human-readable error message.
    /// </summary>
    public required string Message
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("message");
        }
        init { this._rawData.Set("message", value); }
    }

    /// <summary>
    /// Machine-readable error code.
    /// </summary>
    public string? Code
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("code");
        }
        init { this._rawData.Set("code", value); }
    }

    /// <summary>
    /// Suggested action for the user.
    /// </summary>
    public string? Recommendation
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("recommendation");
        }
        init { this._rawData.Set("recommendation", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Message;
        _ = this.Code;
        _ = this.Recommendation;
    }

    public McpServerErrorsItem() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public McpServerErrorsItem(McpServerErrorsItem mcpServerErrorsItem)
        : base(mcpServerErrorsItem) { }
#pragma warning restore CS8618

    public McpServerErrorsItem(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    McpServerErrorsItem(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="McpServerErrorsItemFromRaw.FromRawUnchecked"/>
    public static McpServerErrorsItem FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public McpServerErrorsItem(string message)
        : this()
    {
        this.Message = message;
    }
}

class McpServerErrorsItemFromRaw : IFromRawJson<McpServerErrorsItem>
{
    /// <inheritdoc/>
    public McpServerErrorsItem FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        McpServerErrorsItem.FromRawUnchecked(rawData);
}

/// <summary>
/// The object type, always 'response'
/// </summary>
[JsonConverter(typeof(ObjectConverter))]
public enum Object
{
    Response,
}

sealed class ObjectConverter : JsonConverter<global::DedalusSdk.Models.Responses.Object>
{
    public override global::DedalusSdk.Models.Responses.Object Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "response" => global::DedalusSdk.Models.Responses.Object.Response,
            _ => (global::DedalusSdk.Models.Responses.Object)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        global::DedalusSdk.Models.Responses.Object value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                global::DedalusSdk.Models.Responses.Object.Response => "response",
                _ => throw new DedalusInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// Tool choice configuration used
/// </summary>
[JsonConverter(typeof(ResponseToolChoiceConverter))]
public record class ResponseToolChoice : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public ResponseToolChoice(string value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public ResponseToolChoice(
        IReadOnlyDictionary<string, JsonValueInput?> value,
        JsonElement? element = null
    )
    {
        this.Value = FrozenDictionary.ToFrozenDictionary(value);
        this._element = element;
    }

    public ResponseToolChoice(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="string"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickString(out var value)) {
    ///     // `value` is of type `string`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickString([NotNullWhen(true)] out string? value)
    {
        value = this.Value as string;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="Dictionary{Key, Value}"/> with a <c>Key</c> of <c>string</c> and a <c>Value</c> of <c>JsonValueInput?</c>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickJsonObjectInput(out var value)) {
    ///     // `value` is of type `IReadOnlyDictionary&lt;string, JsonValueInput?&gt;`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickJsonObjectInput(
        [NotNullWhen(true)] out IReadOnlyDictionary<string, JsonValueInput?>? value
    )
    {
        value = this.Value as IReadOnlyDictionary<string, JsonValueInput?>;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (string value) =&gt; {...},
    ///     (IReadOnlyDictionary&lt;string, JsonValueInput?&gt; value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        Action<string> @string,
        Action<IReadOnlyDictionary<string, JsonValueInput?>> jsonObjectInput
    )
    {
        switch (this.Value)
        {
            case string value:
                @string(value);
                break;
            case IReadOnlyDictionary<string, JsonValueInput?> value:
                jsonObjectInput(value);
                break;
            default:
                throw new DedalusInvalidDataException(
                    "Data did not match any variant of ResponseToolChoice"
                );
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (string value) =&gt; {...},
    ///     (IReadOnlyDictionary&lt;string, JsonValueInput?&gt; value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        Func<string, T> @string,
        Func<IReadOnlyDictionary<string, JsonValueInput?>, T> jsonObjectInput
    )
    {
        return this.Value switch
        {
            string value => @string(value),
            IReadOnlyDictionary<string, JsonValueInput?> value => jsonObjectInput(value),
            _ => throw new DedalusInvalidDataException(
                "Data did not match any variant of ResponseToolChoice"
            ),
        };
    }

    public static implicit operator ResponseToolChoice(string value) => new(value);

    public static implicit operator ResponseToolChoice(Dictionary<string, JsonValueInput?> value) =>
        new((IReadOnlyDictionary<string, JsonValueInput?>)value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="DedalusInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new DedalusInvalidDataException(
                "Data did not match any variant of ResponseToolChoice"
            );
        }
        this.Switch(
            (_) => { },
            (jsonObjectInput) =>
            {
                foreach (var item in jsonObjectInput.Values)
                {
                    item?.Validate();
                }
            }
        );
    }

    public virtual bool Equals(ResponseToolChoice? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            string _ => 0,
            IReadOnlyDictionary<string, JsonValueInput?> _ => 1,
            _ => -1,
        };
    }
}

sealed class ResponseToolChoiceConverter : JsonConverter<ResponseToolChoice?>
{
    public override ResponseToolChoice? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        try
        {
            var deserialized = JsonSerializer.Deserialize<string>(element, options);
            if (deserialized != null)
            {
                return new(deserialized, element);
            }
        }
        catch (Exception e) when (e is JsonException || e is DedalusInvalidDataException)
        {
            // ignore
        }

        try
        {
            var deserialized = JsonSerializer.Deserialize<Dictionary<string, JsonValueInput?>>(
                element,
                options
            );
            if (deserialized != null)
            {
                foreach (var item in deserialized.Values)
                {
                    item?.Validate();
                }
                return new(deserialized, element);
            }
        }
        catch (Exception e) when (e is JsonException || e is DedalusInvalidDataException)
        {
            // ignore
        }

        return new(element);
    }

    public override void Write(
        Utf8JsonWriter writer,
        ResponseToolChoice? value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value?.Json, options);
    }
}
